import { randomUUID } from "crypto";
import { and, desc, eq, inArray } from "drizzle-orm";
import { z } from "zod";
import { accountCommercialSignals, accounts, aiCallAssistDrafts, aiInvocationEvents, aiNextBestActions, aiTenantPolicies, plannedVisits, visitLogs } from "../../drizzle/schema";
import { appendAuditEvent, getDb } from "../db";
import { storageGetSignedUrl, storagePut } from "../storage";
import { transcribeAudio } from "../_core/voiceTranscription";
import { resolveTenantScope } from "../security/access";
import { hashAiPayload, invokeAiRoute, resolveAiRoute } from "../services/aiGateway";
import { callAssistOutputSchema, parseCallAssistDraft } from "../services/callAssist";
import { rankNextBestActions } from "../services/nextBestAction";
import { router, tenantRoleProcedure } from "../_core/trpc";

const managerRoles = ["admin", "manager"] as const; const readerRoles = ["admin", "manager", "rep", "exec"] as const; const providers = ["openai", "anthropic", "gemini", "local", "manus"] as const;
type Policy = typeof aiTenantPolicies.$inferSelect;
async function policyForTenant(tenantId: string, userId: number): Promise<Policy> { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [existing] = await db.select().from(aiTenantPolicies).where(eq(aiTenantPolicies.tenantId, tenantId)).limit(1); if (existing) return existing; const id = randomUUID(); const values = { id, tenantId, dataSensitivity: "standard" as const, defaultProvider: "manus" as const, defaultModel: "gpt-5-mini", localModel: null, taskRoutes: {}, createdBy: userId }; await db.insert(aiTenantPolicies).values(values); return { ...values, status: "active", createdAt: new Date(), updatedAt: new Date() } as Policy; }
async function accountForTenant(tenantId: string, accountId: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [row] = await db.select().from(accounts).where(and(eq(accounts.tenantId, tenantId), eq(accounts.id, accountId))).limit(1); if (!row) throw new Error("Account was not found in the active tenant"); return row; }
async function recordInvocation(values: Omit<typeof aiInvocationEvents.$inferInsert, "id">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(aiInvocationEvents).values({ id, ...values }); return id; }

export const aiRouter = router({
  policy: router({
    get: tenantRoleProcedure(managerRoles).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); return policyForTenant(scope.tenantId, scope.userId); }),
    update: tenantRoleProcedure(managerRoles).input(z.object({ dataSensitivity: z.enum(["standard", "sensitive"]), defaultProvider: z.enum(providers), defaultModel: z.string().trim().min(2).max(160), localModel: z.string().trim().min(2).max(160).optional(), taskRoutes: z.record(z.string(), z.object({ provider: z.enum(providers), model: z.string().trim().min(2).max(160) })).default({}) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const current = await policyForTenant(scope.tenantId, scope.userId); if (input.dataSensitivity === "sensitive" && !input.localModel && input.defaultProvider !== "local") throw new Error("Sensitive tenants require a configured local model"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(aiTenantPolicies).set({ ...input, localModel: input.localModel ?? null }).where(and(eq(aiTenantPolicies.id, current.id), eq(aiTenantPolicies.tenantId, scope.tenantId))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "ai_tenant_policy", entityId: current.id, eventType: "ai.policy_updated", operation: "status_change", oldValue: { dataSensitivity: current.dataSensitivity, defaultProvider: current.defaultProvider, defaultModel: current.defaultModel }, newValue: input, reason: "Tenant AI routing policy updated" }); return { id: current.id }; }),
  }),
  callAssist: router({
    transcribe: tenantRoleProcedure(["admin", "manager", "rep"] as const).input(z.object({ audioBase64: z.string().min(20).max(22_400_000), mimeType: z.enum(["audio/webm", "audio/mpeg", "audio/wav", "audio/ogg", "audio/mp4"]), language: z.string().regex(/^[a-z]{2}$/).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const audio = Buffer.from(input.audioBase64, "base64"); if (!audio.length || audio.length > 16 * 1024 * 1024) throw new Error("Dictated note audio must be a supported file no larger than 16MB"); const extension = input.mimeType === "audio/webm" ? "webm" : input.mimeType === "audio/wav" ? "wav" : input.mimeType === "audio/ogg" ? "ogg" : input.mimeType === "audio/mp4" ? "m4a" : "mp3"; const stored = await storagePut(`tenants/${scope.tenantId}/ai-dictation/${scope.userId}-${randomUUID()}.${extension}`, audio, input.mimeType); const result = await transcribeAudio({ audioUrl: await storageGetSignedUrl(stored.key), language: input.language, prompt: "Transcribe a pharmaceutical field representative's private visit note accurately. Preserve product names and next steps." }); if ("error" in result) throw new Error(result.error); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "ai_dictation", entityId: randomUUID(), eventType: "ai.dictation_transcribed", operation: "access", oldValue: null, newValue: { audioHash: hashAiPayload(audio.toString("base64")), language: result.language, duration: result.duration }, reason: "Private dictated note transcribed for reviewable AI call assistance" }); return { text: result.text, language: result.language, duration: result.duration }; }),
    generate: tenantRoleProcedure(["admin", "manager", "rep"] as const).input(z.object({ note: z.string().trim().min(10).max(12000), accountId: z.string().uuid().optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); if (input.accountId) await accountForTenant(scope.tenantId, input.accountId); const policy = await policyForTenant(scope.tenantId, scope.userId); if (policy.status !== "active") throw new Error("AI is disabled for this tenant"); const route = resolveAiRoute(policy as any, "call_assist"); const started = Date.now(); const base = { tenantId: scope.tenantId, policyId: policy.id, actorUserId: scope.userId, task: "call_assist" as const, provider: route.provider, model: route.model, inputHash: hashAiPayload({ note: input.note, accountId: input.accountId }), createdBy: scope.userId }; try { const result = await invokeAiRoute(route, { system: "You structure pharmaceutical field-visit notes. Return only the requested JSON. Do not invent samples, clinical claims, or signatures. The output is a user-reviewable draft and must never be treated as a finalized regulated record.", input: input.note, schema: callAssistOutputSchema }); const draft = parseCallAssistDraft(result.content); const invocationId = await recordInvocation({ ...base, status: "completed", outputHash: hashAiPayload(draft), latencyMs: Date.now() - started, promptTokens: result.promptTokens ?? null, completionTokens: result.completionTokens ?? null, failureReason: null }); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(aiCallAssistDrafts).values({ id, tenantId: scope.tenantId, invocationId, repUserId: scope.userId, accountId: input.accountId ?? null, sourceNoteHash: base.inputHash, structuredDraft: draft, confidence: draft.confidence, createdBy: scope.userId }); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "ai_call_assist_draft", entityId: id, eventType: "ai.call_assist_generated", operation: "create", oldValue: null, newValue: { invocationId, accountId: input.accountId ?? null, confidence: draft.confidence }, reason: "AI generated a reviewable visit-note draft" }); return { id, invocationId, draft, route }; } catch (error) { await recordInvocation({ ...base, status: "failed", outputHash: null, latencyMs: Date.now() - started, promptTokens: null, completionTokens: null, failureReason: error instanceof Error ? error.message.slice(0, 500) : "AI request failed" }); throw error; } }),
    list: tenantRoleProcedure(readerRoles).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; return db.select().from(aiCallAssistDrafts).where(and(eq(aiCallAssistDrafts.tenantId, scope.tenantId), ...(scope.role === "rep" ? [eq(aiCallAssistDrafts.repUserId, scope.userId)] : []))).orderBy(desc(aiCallAssistDrafts.createdAt)); }),
    setStatus: tenantRoleProcedure(["admin", "manager", "rep"] as const).input(z.object({ id: z.string().uuid(), status: z.enum(["accepted", "discarded"]) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [draft] = await db.select().from(aiCallAssistDrafts).where(and(eq(aiCallAssistDrafts.tenantId, scope.tenantId), eq(aiCallAssistDrafts.id, input.id), ...(scope.role === "rep" ? [eq(aiCallAssistDrafts.repUserId, scope.userId)] : []))).limit(1); if (!draft) throw new Error("AI call-assist draft was not found in the active tenant"); await db.update(aiCallAssistDrafts).set({ status: input.status }).where(and(eq(aiCallAssistDrafts.id, input.id), eq(aiCallAssistDrafts.tenantId, scope.tenantId))); return { success: true }; }),
  }),
  commercialSignals: router({
    list: tenantRoleProcedure(managerRoles).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(accountCommercialSignals).where(eq(accountCommercialSignals.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(accountCommercialSignals.observedAt)); }),
    record: tenantRoleProcedure(managerRoles).input(z.object({ accountId: z.string().uuid(), signalType: z.enum(["sales", "prescribing"]), value: z.string().regex(/^\d+(\.\d{1,2})?$/), observedAt: z.date(), source: z.string().trim().min(2).max(160) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); await accountForTenant(scope.tenantId, input.accountId); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(accountCommercialSignals).values({ id, tenantId: scope.tenantId, ...input, createdBy: scope.userId }); return { id }; }),
  }),
  nextBestAction: router({
    generate: tenantRoleProcedure(["admin", "manager", "rep"] as const).input(z.object({ repUserId: z.number().int().positive().optional() }).optional()).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const repUserId = scope.role === "rep" ? scope.userId : input?.repUserId ?? scope.userId; const db = await getDb(); if (!db) return []; const [tenantAccounts, visits, signals, callPlan] = await Promise.all([db.select().from(accounts).where(and(eq(accounts.tenantId, scope.tenantId), eq(accounts.status, "active"))), db.select().from(visitLogs).where(and(eq(visitLogs.tenantId, scope.tenantId), eq(visitLogs.repUserId, repUserId))), db.select().from(accountCommercialSignals).where(and(eq(accountCommercialSignals.tenantId, scope.tenantId), eq(accountCommercialSignals.status, "active"))), db.select().from(plannedVisits).where(and(eq(plannedVisits.tenantId, scope.tenantId), eq(plannedVisits.repUserId, repUserId), inArray(plannedVisits.status, ["planned", "rescheduled"])))]); const plannedAccountIds = new Set(callPlan.map(item => item.accountId)); const scopedAccounts = plannedAccountIds.size ? tenantAccounts.filter(account => plannedAccountIds.has(account.id)) : tenantAccounts; const latest = new Map<string, Date>(); for (const visit of visits) if (visit.accountId && (!latest.get(visit.accountId) || latest.get(visit.accountId)! < visit.occurredAt)) latest.set(visit.accountId, visit.occurredAt); const signalsByAccount = new Map<string, { sales?: number; prescribing?: number }>(); for (const signal of signals) { const item = signalsByAccount.get(signal.accountId) ?? {}; if (signal.signalType === "sales") item.sales = Math.max(item.sales ?? 0, Number(signal.value)); else item.prescribing = Math.max(item.prescribing ?? 0, Number(signal.value)); signalsByAccount.set(signal.accountId, item); } const actions = rankNextBestActions(scopedAccounts.map(account => ({ accountId: account.id, accountName: account.name, tier: account.tier, lastVisitAt: latest.get(account.id), salesSignal: signalsByAccount.get(account.id)?.sales, prescribingSignal: signalsByAccount.get(account.id)?.prescribing }))).slice(0, 10); const now = new Date(); if (actions.length) await db.insert(aiNextBestActions).values(actions.map((item, index) => ({ id: randomUUID(), tenantId: scope.tenantId, invocationId: null, repUserId, accountId: item.accountId, rank: index + 1, score: item.score, reasonComponents: item.reasonComponents, recommendation: item.recommendation, generatedAt: now, createdBy: scope.userId }))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "next_best_action_batch", entityId: randomUUID(), eventType: "ai.next_best_action_generated", operation: "create", oldValue: null, newValue: { repUserId, count: actions.length, constrainedToCallPlan: plannedAccountIds.size > 0 }, reason: "Explainable account prioritization generated from tenant CRM signals" }); return actions; }),
    list: tenantRoleProcedure(readerRoles).input(z.object({ repUserId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const repUserId = scope.role === "rep" ? scope.userId : input?.repUserId ?? scope.userId; const db = await getDb(); if (!db) return []; return db.select().from(aiNextBestActions).where(and(eq(aiNextBestActions.tenantId, scope.tenantId), eq(aiNextBestActions.repUserId, repUserId), eq(aiNextBestActions.status, "generated"))).orderBy(aiNextBestActions.rank); }),
  }),
});
