import { randomUUID } from "crypto";
import { and, desc, eq } from "drizzle-orm";
import { parse as parseCookie } from "cookie";
import { z } from "zod";
import { analyticsQueries, anomalyAlertReviews, anomalyAlerts, anomalyMonitorConfigs } from "../../drizzle/schema";
import { COOKIE_NAME } from "../../shared/const";
import { appendAuditEvent, getDb } from "../db";
import { createHeartbeatJob, updateHeartbeatJob } from "../_core/heartbeat";
import { router, tenantRoleProcedure } from "../_core/trpc";
import { resolveTenantScope } from "../security/access";
import { planAnalyticsQuestion, runAnalyticsPlan } from "../services/analytics";
import { runDailyAnomalyDetection } from "../services/anomalyDetection";

const managers = ["admin", "manager"] as const;
async function monitorFor(tenantId: string, userId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [existing] = await db.select().from(anomalyMonitorConfigs).where(eq(anomalyMonitorConfigs.tenantId, tenantId)).limit(1); if (existing) return existing; const created = { id: randomUUID(), tenantId, createdBy: userId, enabled: 1, cronExpression: "0 0 2 * * *", sampleMultiplier: 3, expenseMultiplier: 2, territoryLookbackHours: 24, scheduleCronTaskUid: null, lastRunAt: null }; await db.insert(anomalyMonitorConfigs).values(created); return { ...created, createdAt: new Date(), updatedAt: new Date() } as typeof anomalyMonitorConfigs.$inferSelect; }

export const analyticsRouter = router({
  ask: tenantRoleProcedure(["admin", "manager", "exec"] as const).input(z.object({ question: z.string().trim().min(3).max(500) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); try { const plan = planAnalyticsQuestion(input.question); const result = await runAnalyticsPlan(scope.tenantId, plan); await db.insert(analyticsQueries).values({ id, tenantId: scope.tenantId, userId: scope.userId, question: input.question, semanticPlan: result.plan, resultSummary: result.summary, chartSpec: { chart: result.plan.chart, xKey: result.plan.xKey, yKey: result.plan.yKey, columns: result.columns, rows: result.rows }, status: "completed", createdBy: scope.userId }); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "analytics_query", entityId: id, eventType: "analytics.query_completed", operation: "access", oldValue: null, newValue: { intent: result.plan.intent, rowCount: result.rows.length }, reason: "Allow-listed semantic analytics query completed" }); return result; } catch (error) { await db.insert(analyticsQueries).values({ id, tenantId: scope.tenantId, userId: scope.userId, question: input.question, status: "rejected", rejectionReason: error instanceof Error ? error.message.slice(0, 500) : "Rejected", createdBy: scope.userId }); throw error; } }),
  history: tenantRoleProcedure(["admin", "manager", "exec"] as const).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); return db ? db.select().from(analyticsQueries).where(and(eq(analyticsQueries.tenantId, scope.tenantId), eq(analyticsQueries.userId, scope.userId))).orderBy(desc(analyticsQueries.createdAt)) : []; }),
  monitor: router({
    get: tenantRoleProcedure(managers).query(async ({ ctx }) => monitorFor(resolveTenantScope(ctx.user!).tenantId, resolveTenantScope(ctx.user!).userId)),
    configure: tenantRoleProcedure(managers).input(z.object({ enabled: z.boolean(), sampleMultiplier: z.number().int().min(2).max(10), expenseMultiplier: z.number().int().min(2).max(10), territoryLookbackHours: z.number().int().min(12).max(72) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const config = await monitorFor(scope.tenantId, scope.userId); const db = await getDb(); if (!db) throw new Error("Database unavailable"); let taskUid = config.scheduleCronTaskUid; const session = parseCookie(ctx.req.headers.cookie ?? "")[COOKIE_NAME] ?? ""; if (input.enabled && !taskUid) { const job = await createHeartbeatJob({ name: `anomaly-${config.id}`, cron: config.cronExpression, path: "/api/scheduled/anomaly-monitor", payload: {}, description: `Daily anomaly monitor for tenant ${scope.tenantId}` }, session); taskUid = job.taskUid; } else if (taskUid) await updateHeartbeatJob(taskUid, { enable: input.enabled }, session); await db.update(anomalyMonitorConfigs).set({ ...input, enabled: input.enabled ? 1 : 0, scheduleCronTaskUid: taskUid }).where(and(eq(anomalyMonitorConfigs.id, config.id), eq(anomalyMonitorConfigs.tenantId, scope.tenantId))); return { id: config.id, taskUid }; }),
    runNow: tenantRoleProcedure(managers).mutation(async ({ ctx }) => runDailyAnomalyDetection(await monitorFor(resolveTenantScope(ctx.user!).tenantId, resolveTenantScope(ctx.user!).userId))),
  }),
  alerts: router({
    list: tenantRoleProcedure(managers).input(z.object({ status: z.enum(["open", "acknowledged", "resolved", "dismissed"]).optional() }).optional()).query(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; return db.select().from(anomalyAlerts).where(and(eq(anomalyAlerts.tenantId, scope.tenantId), ...(input?.status ? [eq(anomalyAlerts.status, input.status)] : []))).orderBy(desc(anomalyAlerts.detectedAt)); }),
    review: tenantRoleProcedure(managers).input(z.object({ id: z.string().uuid(), action: z.enum(["acknowledged", "resolved", "dismissed", "reopened"]), note: z.string().trim().max(2000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [alert] = await db.select().from(anomalyAlerts).where(and(eq(anomalyAlerts.id, input.id), eq(anomalyAlerts.tenantId, scope.tenantId))).limit(1); if (!alert) throw new Error("Alert was not found in the active tenant"); const status = input.action === "reopened" ? "open" : input.action; await db.insert(anomalyAlertReviews).values({ id: randomUUID(), tenantId: scope.tenantId, alertId: alert.id, action: input.action, note: input.note ?? null, createdBy: scope.userId }); await db.update(anomalyAlerts).set({ status, lastReviewedAt: new Date() }).where(and(eq(anomalyAlerts.id, alert.id), eq(anomalyAlerts.tenantId, scope.tenantId))); return { success: true }; }),
  }),
});
