import { randomUUID } from "crypto";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { accounts, contacts, cyclePlans, opportunities, plannedVisits, territories } from "../../drizzle/schema";
import { appendAuditEvent, getDb } from "../db";
import { resolveTenantScope } from "../security/access";
import { router, tenantRoleProcedure } from "../_core/trpc";

const managerRoles = ["admin", "manager"] as const;
const readableRoles = ["admin", "manager", "rep", "exec"] as const;
export function opportunityStatusForStage(stage: "qualification" | "discovery" | "proposal" | "negotiation" | "won" | "lost") {
  return stage === "won" ? "won" : stage === "lost" ? "lost" : "open";
}
const accountInput = z.object({ accountType: z.enum(["hcp", "pharmacy", "hospital", "distributor", "organization"]), name: z.string().trim().min(2).max(255), specialty: z.string().trim().max(160).optional(), tier: z.enum(["a", "b", "c", "unclassified"]).default("unclassified"), territoryId: z.string().uuid().optional(), email: z.string().email().optional(), phone: z.string().max(64).optional(), address: z.string().max(3000).optional() });

async function accountForTenant(tenantId: string, accountId: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [row] = await db.select().from(accounts).where(and(eq(accounts.tenantId, tenantId), eq(accounts.id, accountId))).limit(1); if (!row) throw new Error("CRM account not found in the active tenant"); return row; }

export const crmRouter = router({
  accounts: router({
    list: tenantRoleProcedure(readableRoles).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(accounts).where(eq(accounts.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(accounts.updatedAt)); }),
    create: tenantRoleProcedure(managerRoles).input(accountInput).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(accounts).values({ id, tenantId: scope.tenantId, ...input, specialty: input.specialty ?? null, territoryId: input.territoryId ?? null, email: input.email ?? null, phone: input.phone ?? null, address: input.address ?? null, createdBy: scope.userId }); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "account", entityId: id, eventType: "account.created", operation: "create", oldValue: null, newValue: { name: input.name, accountType: input.accountType }, reason: "CRM account created" }); return { id }; }),
  }),
  contacts: router({
    list: tenantRoleProcedure(readableRoles).input(z.object({ accountId: z.string().uuid().optional() }).optional()).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return []; const scope = resolveTenantScope(ctx.user!); return db.select().from(contacts).where(input?.accountId ? and(eq(contacts.tenantId, scope.tenantId), eq(contacts.accountId, input.accountId)) : eq(contacts.tenantId, scope.tenantId)).orderBy(desc(contacts.updatedAt)); }),
    create: tenantRoleProcedure(managerRoles).input(z.object({ accountId: z.string().uuid(), firstName: z.string().trim().min(1).max(128), lastName: z.string().trim().min(1).max(128), title: z.string().max(160).optional(), email: z.string().email().optional(), phone: z.string().max(64).optional(), preferredChannel: z.enum(["email", "phone", "in_person", "whatsapp", "other"]).default("email") })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); await accountForTenant(scope.tenantId, input.accountId); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(contacts).values({ id, tenantId: scope.tenantId, ...input, title: input.title ?? null, email: input.email ?? null, phone: input.phone ?? null, createdBy: scope.userId }); return { id }; }),
  }),
  territories: router({
    list: tenantRoleProcedure(readableRoles).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(territories).where(eq(territories.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(territories.updatedAt)); }),
    create: tenantRoleProcedure(managerRoles).input(z.object({ name: z.string().trim().min(2).max(180), code: z.string().trim().toUpperCase().min(2).max(64), region: z.string().max(120).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(territories).values({ id, tenantId: scope.tenantId, ...input, region: input.region ?? null, createdBy: scope.userId }); return { id }; }),
  }),
  plans: router({
    list: tenantRoleProcedure(readableRoles).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(cyclePlans).where(eq(cyclePlans.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(cyclePlans.startDate)); }),
    create: tenantRoleProcedure(managerRoles).input(z.object({ name: z.string().trim().min(2).max(255), description: z.string().max(3000).optional(), startDate: z.date(), endDate: z.date() }).refine(v => v.endDate >= v.startDate, { message: "End date must be after start date." })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(cyclePlans).values({ id, tenantId: scope.tenantId, ...input, description: input.description ?? null, createdBy: scope.userId }); return { id }; }),
    schedule: tenantRoleProcedure(managerRoles).input(z.object({ cyclePlanId: z.string().uuid(), accountId: z.string().uuid(), repUserId: z.number().int().positive(), plannedStartAt: z.date(), priority: z.enum(["critical", "high", "normal", "low"]).default("normal"), objective: z.string().max(3000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); await accountForTenant(scope.tenantId, input.accountId); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(plannedVisits).values({ id, tenantId: scope.tenantId, ...input, objective: input.objective ?? null, createdBy: scope.userId }); return { id }; }),
  }),
  opportunities: router({
    list: tenantRoleProcedure(readableRoles).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(opportunities).where(eq(opportunities.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(opportunities.updatedAt)); }),
    create: tenantRoleProcedure(managerRoles).input(z.object({ name: z.string().trim().min(2).max(255), accountId: z.string().uuid().optional(), value: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0.00"), probability: z.number().int().min(0).max(100).default(10), expectedCloseDate: z.date().optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); if (input.accountId) await accountForTenant(scope.tenantId, input.accountId); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(opportunities).values({ id, tenantId: scope.tenantId, ...input, accountId: input.accountId ?? null, expectedCloseDate: input.expectedCloseDate ?? null, ownerUserId: scope.userId, createdBy: scope.userId }); return { id }; }),
    moveStage: tenantRoleProcedure(managerRoles).input(z.object({ id: z.string().uuid(), stage: z.enum(["qualification", "discovery", "proposal", "negotiation", "won", "lost"]) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [opportunity] = await db.select().from(opportunities).where(and(eq(opportunities.tenantId, scope.tenantId), eq(opportunities.id, input.id))).limit(1); if (!opportunity) throw new Error("Opportunity not found in the active tenant"); const status = opportunityStatusForStage(input.stage); await db.update(opportunities).set({ stage: input.stage, status }).where(and(eq(opportunities.id, input.id), eq(opportunities.tenantId, scope.tenantId))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "opportunity", entityId: input.id, eventType: "opportunity.stage_changed", operation: "status_change", oldValue: { stage: opportunity.stage }, newValue: { stage: input.stage, status }, reason: "Opportunity Kanban stage transition" }); return { id: input.id }; }),
  }),
});
