import { randomUUID } from "crypto";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { accounts, coachingScorecards, contacts, fieldEventAttendees, fieldEvents, fleetMaintenanceRecords, fleetVehicles, fuelLogs, procurementRequests, purchaseOrders, rideAlongSessions, territories, territoryForecasts, users, visitCoachingNotes, visitLogs } from "../../drizzle/schema";
import { appendAuditEvent, getDb } from "../db";
import { resolveTenantScope } from "../security/access";
import { router, tenantRoleProcedure } from "../_core/trpc";

const staff = ["admin", "manager", "rep", "hr", "exec"] as const;
const managers = ["admin", "manager"] as const;
const operators = ["admin", "manager", "hr"] as const;
const date = z.coerce.date();
const requiredReason = z.string().trim().min(3).max(2000);
const ownOrManager = (role: string) => role === "admin" || role === "manager";

async function tenantRow<T extends { tenantId: any; id: any }>(db: any, table: T, tenantId: string, id: string, label: string) {
  const [row] = await db.select().from(table).where(and(eq(table.tenantId, tenantId), eq(table.id, id))).limit(1);
  if (!row) throw new Error(`${label} was not found in the active tenant`);
  return row;
}
async function evidence(scope: ReturnType<typeof resolveTenantScope>, entityType: string, entityId: string, eventType: string, operation: "create" | "status_change" | "access", newValue: unknown, reason: string) {
  await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType, entityId, eventType, operation, oldValue: null, newValue, reason });
}

export const expansionRouter = router({
  forecasts: router({
    list: tenantRoleProcedure(["admin", "manager", "exec"] as const).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); return db ? db.select().from(territoryForecasts).where(eq(territoryForecasts.tenantId, scope.tenantId)).orderBy(desc(territoryForecasts.periodStart)) : []; }),
    create: tenantRoleProcedure(managers).input(z.object({ territoryId: z.string().uuid().optional(), productName: z.string().trim().min(2).max(255), periodStart: date, periodEnd: date, method: z.enum(["manual", "moving_average"]), forecastValue: z.number().nonnegative().optional(), historicalValues: z.array(z.number().nonnegative()).max(24).optional(), confidencePct: z.number().int().min(1).max(99).default(50) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); if (input.periodEnd < input.periodStart) throw new Error("Forecast period end must follow start"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); if (input.territoryId) await tenantRow(db, territories, scope.tenantId, input.territoryId, "Territory"); const history = input.historicalValues ?? []; const historicalActual = history.length ? history.reduce((sum, value) => sum + value, 0) / history.length : 0; const forecastValue = input.method === "moving_average" ? historicalActual : input.forecastValue; if (forecastValue === undefined) throw new Error("Manual forecast value is required"); const id = randomUUID(); await db.insert(territoryForecasts).values({ id, tenantId: scope.tenantId, territoryId: input.territoryId ?? null, productName: input.productName, periodStart: input.periodStart, periodEnd: input.periodEnd, historicalActual: String(historicalActual), forecastValue: String(forecastValue), method: input.method, confidencePct: input.confidencePct, createdBy: scope.userId }); await evidence(scope, "territory_forecast", id, "forecast.created", "create", { ...input, historicalActual, forecastValue }, "Tenant forecast created"); return { id, historicalActual, forecastValue }; }),
    publish: tenantRoleProcedure(managers).input(z.object({ id: z.string().uuid() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const row = await tenantRow(db, territoryForecasts, scope.tenantId, input.id, "Forecast"); if (row.status !== "draft") throw new Error("Only draft forecasts can be published"); await db.update(territoryForecasts).set({ status: "published" }).where(and(eq(territoryForecasts.id, input.id), eq(territoryForecasts.tenantId, scope.tenantId))); await evidence(scope, "territory_forecast", input.id, "forecast.published", "status_change", { status: "published" }, "Forecast published"); return { success: true }; }),
  }),
  procurement: router({
    list: tenantRoleProcedure(staff).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; const filter = ownOrManager(scope.role) || scope.role === "hr" ? [] : [eq(procurementRequests.createdBy, scope.userId)]; return db.select().from(procurementRequests).where(and(eq(procurementRequests.tenantId, scope.tenantId), ...filter)).orderBy(desc(procurementRequests.createdAt)); }),
    submit: tenantRoleProcedure(staff).input(z.object({ productName: z.string().trim().min(2).max(255), sku: z.string().trim().max(128).optional(), requestedQuantity: z.number().int().positive().max(1_000_000), neededBy: date.optional(), rationale: requiredReason.optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(procurementRequests).values({ id, tenantId: scope.tenantId, ...input, sku: input.sku ?? null, neededBy: input.neededBy ?? null, rationale: input.rationale ?? null, createdBy: scope.userId }); await evidence(scope, "procurement_request", id, "procurement.submitted", "create", input, "Procurement request submitted"); return { id }; }),
    review: tenantRoleProcedure(operators).input(z.object({ id: z.string().uuid(), status: z.enum(["approved", "rejected"]), note: requiredReason })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const row = await tenantRow(db, procurementRequests, scope.tenantId, input.id, "Procurement request"); if (row.status !== "submitted") throw new Error("Only submitted requests can be reviewed"); await db.update(procurementRequests).set({ status: input.status, reviewerUserId: scope.userId, reviewedAt: new Date(), reviewNote: input.note }).where(and(eq(procurementRequests.id, input.id), eq(procurementRequests.tenantId, scope.tenantId))); await evidence(scope, "procurement_request", input.id, `procurement.${input.status}`, "status_change", input, "Procurement request reviewed"); return { success: true }; }),
    createOrder: tenantRoleProcedure(operators).input(z.object({ requestId: z.string().uuid(), supplierName: z.string().trim().min(2).max(255), orderedQuantity: z.number().int().positive(), unitCost: z.number().nonnegative(), currency: z.string().length(3).default("USD"), expectedDeliveryDate: date.optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const request = await tenantRow(db, procurementRequests, scope.tenantId, input.requestId, "Procurement request"); if (request.status !== "approved") throw new Error("Only approved requests can receive purchase orders"); const id = randomUUID(); await db.insert(purchaseOrders).values({ id, tenantId: scope.tenantId, ...input, unitCost: String(input.unitCost), currency: input.currency.toUpperCase(), expectedDeliveryDate: input.expectedDeliveryDate ?? null, createdBy: scope.userId }); await db.update(procurementRequests).set({ status: "ordered" }).where(and(eq(procurementRequests.id, input.requestId), eq(procurementRequests.tenantId, scope.tenantId))); await evidence(scope, "purchase_order", id, "procurement.order_issued", "create", input, "Approved procurement request converted to purchase order"); return { id }; }),
  }),
  fleet: router({
    vehicles: router({ list: tenantRoleProcedure(staff).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); return db ? db.select().from(fleetVehicles).where(eq(fleetVehicles.tenantId, scope.tenantId)).orderBy(desc(fleetVehicles.createdAt)) : []; }), create: tenantRoleProcedure(managers).input(z.object({ registrationNumber: z.string().trim().min(2).max(64), makeModel: z.string().trim().min(2).max(255), assignedUserId: z.number().int().positive().optional(), odometerKm: z.number().int().nonnegative().default(0) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(fleetVehicles).values({ id, tenantId: scope.tenantId, ...input, assignedUserId: input.assignedUserId ?? null, createdBy: scope.userId }); await evidence(scope, "fleet_vehicle", id, "fleet.vehicle_created", "create", input, "Fleet vehicle registered"); return { id }; }) }),
    maintenance: router({ list: tenantRoleProcedure(staff).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); return db ? db.select().from(fleetMaintenanceRecords).where(eq(fleetMaintenanceRecords.tenantId, scope.tenantId)).orderBy(desc(fleetMaintenanceRecords.createdAt)) : []; }), schedule: tenantRoleProcedure(managers).input(z.object({ vehicleId: z.string().uuid(), maintenanceType: z.string().trim().min(2).max(160), dueDate: date.optional(), dueOdometerKm: z.number().int().nonnegative().optional(), notes: z.string().max(2000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await tenantRow(db, fleetVehicles, scope.tenantId, input.vehicleId, "Vehicle"); const id = randomUUID(); await db.insert(fleetMaintenanceRecords).values({ id, tenantId: scope.tenantId, ...input, dueDate: input.dueDate ?? null, dueOdometerKm: input.dueOdometerKm ?? null, notes: input.notes ?? null, createdBy: scope.userId }); await evidence(scope, "fleet_maintenance", id, "fleet.maintenance_scheduled", "create", input, "Vehicle maintenance scheduled"); return { id }; }) }),
    fuel: router({ list: tenantRoleProcedure(staff).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); return db ? db.select().from(fuelLogs).where(eq(fuelLogs.tenantId, scope.tenantId)).orderBy(desc(fuelLogs.filledAt)) : []; }), record: tenantRoleProcedure(staff).input(z.object({ vehicleId: z.string().uuid(), filledAt: date, odometerKm: z.number().int().nonnegative(), liters: z.number().positive(), totalCost: z.number().nonnegative(), currency: z.string().length(3).default("USD"), stationName: z.string().trim().max(255).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await tenantRow(db, fleetVehicles, scope.tenantId, input.vehicleId, "Vehicle"); const id = randomUUID(); await db.insert(fuelLogs).values({ id, tenantId: scope.tenantId, ...input, liters: String(input.liters), totalCost: String(input.totalCost), currency: input.currency.toUpperCase(), stationName: input.stationName ?? null, createdBy: scope.userId }); await db.update(fleetVehicles).set({ odometerKm: input.odometerKm }).where(and(eq(fleetVehicles.id, input.vehicleId), eq(fleetVehicles.tenantId, scope.tenantId))); await evidence(scope, "fuel_log", id, "fleet.fuel_recorded", "create", input, "Manual fleet fuel entry"); return { id }; }) }),
  }),
  events: router({
    list: tenantRoleProcedure(staff).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); return db ? db.select().from(fieldEvents).where(eq(fieldEvents.tenantId, scope.tenantId)).orderBy(desc(fieldEvents.startsAt)) : []; }),
    create: tenantRoleProcedure(managers).input(z.object({ name: z.string().trim().min(2).max(255), eventType: z.enum(["medical_conference", "webinar", "product_launch", "training", "other"]), startsAt: date, endsAt: date, locationOrUrl: z.string().trim().max(768).optional(), description: z.string().max(4000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); if (input.endsAt <= input.startsAt) throw new Error("Event end must follow start"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(fieldEvents).values({ id, tenantId: scope.tenantId, ...input, locationOrUrl: input.locationOrUrl ?? null, description: input.description ?? null, createdBy: scope.userId }); await evidence(scope, "field_event", id, "event.created", "create", input, "Field event created"); return { id }; }),
    addAttendee: tenantRoleProcedure(managers).input(z.object({ eventId: z.string().uuid(), accountId: z.string().uuid().optional(), contactId: z.string().uuid().optional() }).refine(value => value.accountId || value.contactId, { message: "Provide an account or contact" })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await tenantRow(db, fieldEvents, scope.tenantId, input.eventId, "Event"); if (input.accountId) await tenantRow(db, accounts, scope.tenantId, input.accountId, "Account"); if (input.contactId) await tenantRow(db, contacts, scope.tenantId, input.contactId, "Contact"); const id = randomUUID(); await db.insert(fieldEventAttendees).values({ id, tenantId: scope.tenantId, ...input, accountId: input.accountId ?? null, contactId: input.contactId ?? null, createdBy: scope.userId }); await evidence(scope, "field_event_attendee", id, "event.attendee_invited", "create", input, "Event attendee registered"); return { id }; }),
  }),
  coaching: router({
    list: tenantRoleProcedure(["admin", "manager", "rep"] as const).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; return db.select().from(visitCoachingNotes).where(and(eq(visitCoachingNotes.tenantId, scope.tenantId), ...(scope.role === "rep" ? [eq(visitCoachingNotes.repUserId, scope.userId)] : []))).orderBy(desc(visitCoachingNotes.createdAt)); }),
    add: tenantRoleProcedure(managers).input(z.object({ visitLogId: z.string().uuid(), coachingNote: requiredReason, complianceFlag: z.boolean().default(false) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const visit = await tenantRow(db, visitLogs, scope.tenantId, input.visitLogId, "Visit"); const id = randomUUID(); await db.insert(visitCoachingNotes).values({ id, tenantId: scope.tenantId, visitLogId: input.visitLogId, repUserId: visit.repUserId, coachingNote: input.coachingNote, complianceFlag: input.complianceFlag ? 1 : 0, createdBy: scope.userId }); await evidence(scope, "visit_coaching_note", id, "coaching.note_created", "create", input, input.complianceFlag ? "Manager logged a compliance coaching flag" : "Manager logged visit coaching feedback"); return { id }; }),
    acknowledge: tenantRoleProcedure(["rep"] as const).input(z.object({ id: z.string().uuid() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const row = await tenantRow(db, visitCoachingNotes, scope.tenantId, input.id, "Coaching note"); if (row.repUserId !== scope.userId || row.acknowledgementStatus !== "pending") throw new Error("Coaching note cannot be acknowledged"); await db.update(visitCoachingNotes).set({ acknowledgementStatus: "acknowledged", acknowledgedAt: new Date() }).where(and(eq(visitCoachingNotes.id, input.id), eq(visitCoachingNotes.tenantId, scope.tenantId))); await evidence(scope, "visit_coaching_note", input.id, "coaching.acknowledged", "status_change", { acknowledgementStatus: "acknowledged" }, "Representative acknowledged coaching feedback"); return { success: true }; }),
    rideAlongs: router({
      list: tenantRoleProcedure(["admin", "manager", "rep"] as const).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; return db.select().from(rideAlongSessions).where(and(eq(rideAlongSessions.tenantId, scope.tenantId), ...(scope.role === "rep" ? [eq(rideAlongSessions.repUserId, scope.userId)] : []))).orderBy(desc(rideAlongSessions.scheduledFor)); }),
      schedule: tenantRoleProcedure(managers).input(z.object({ repUserId: z.number().int().positive(), scheduledFor: date, objective: z.string().trim().max(3000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [rep] = await db.select().from(users).where(and(eq(users.tenantId, scope.tenantId), eq(users.id, input.repUserId), eq(users.role, "rep"), eq(users.status, "active"))).limit(1); if (!rep) throw new Error("Active representative not found in the tenant"); const id = randomUUID(); await db.insert(rideAlongSessions).values({ id, tenantId: scope.tenantId, managerUserId: scope.userId, repUserId: input.repUserId, scheduledFor: input.scheduledFor, objective: input.objective ?? null, createdBy: scope.userId }); await evidence(scope, "ride_along", id, "coaching.ride_along_scheduled", "create", input, "Manager scheduled ride-along"); return { id }; }),
      complete: tenantRoleProcedure(managers).input(z.object({ id: z.string().uuid(), completionNote: requiredReason })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const row = await tenantRow(db, rideAlongSessions, scope.tenantId, input.id, "Ride-along"); if (row.managerUserId !== scope.userId || row.status !== "planned") throw new Error("Only the scheduling manager can complete a planned ride-along"); await db.update(rideAlongSessions).set({ status: "completed", completionNote: input.completionNote, completedAt: new Date() }).where(and(eq(rideAlongSessions.id, input.id), eq(rideAlongSessions.tenantId, scope.tenantId))); await evidence(scope, "ride_along", input.id, "coaching.ride_along_completed", "status_change", { status: "completed", completionNote: input.completionNote }, "Manager completed ride-along"); return { success: true }; }),
    }),
    scorecards: router({
      list: tenantRoleProcedure(["admin", "manager", "rep"] as const).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; return db.select().from(coachingScorecards).where(and(eq(coachingScorecards.tenantId, scope.tenantId), ...(scope.role === "rep" ? [eq(coachingScorecards.repUserId, scope.userId)] : []))).orderBy(desc(coachingScorecards.createdAt)); }),
      create: tenantRoleProcedure(managers).input(z.object({ rideAlongId: z.string().uuid().optional(), repUserId: z.number().int().positive(), preparationScore: z.number().int().min(1).max(5), productKnowledgeScore: z.number().int().min(1).max(5), callQualityScore: z.number().int().min(1).max(5), complianceScore: z.number().int().min(1).max(5), followUpScore: z.number().int().min(1).max(5), summary: requiredReason, actionPlan: z.string().trim().max(3000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); if (input.rideAlongId) { const rideAlong = await tenantRow(db, rideAlongSessions, scope.tenantId, input.rideAlongId, "Ride-along"); if (rideAlong.repUserId !== input.repUserId || rideAlong.status !== "completed") throw new Error("Scorecard requires a completed ride-along for the same representative"); } const id = randomUUID(); await db.insert(coachingScorecards).values({ id, tenantId: scope.tenantId, ...input, rideAlongId: input.rideAlongId ?? null, actionPlan: input.actionPlan ?? null, createdBy: scope.userId }); await evidence(scope, "coaching_scorecard", id, "coaching.scorecard_created", "create", input, "Manager created coaching scorecard"); return { id }; }),
      acknowledge: tenantRoleProcedure(["rep"] as const).input(z.object({ id: z.string().uuid() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const row = await tenantRow(db, coachingScorecards, scope.tenantId, input.id, "Coaching scorecard"); if (row.repUserId !== scope.userId || row.acknowledgementStatus !== "pending") throw new Error("Scorecard cannot be acknowledged"); await db.update(coachingScorecards).set({ acknowledgementStatus: "acknowledged", acknowledgedAt: new Date() }).where(and(eq(coachingScorecards.id, input.id), eq(coachingScorecards.tenantId, scope.tenantId))); await evidence(scope, "coaching_scorecard", input.id, "coaching.scorecard_acknowledged", "status_change", { acknowledgementStatus: "acknowledged" }, "Representative acknowledged scorecard"); return { success: true }; }),
    }),
  }),
});
