import { randomUUID } from "crypto";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { inventoryReorderLevels, inventorySites, inventoryStockLedger } from "../../drizzle/schema";
import { appendAuditEvent, getDb } from "../db";
import { resolveTenantScope } from "../security/access";
import { router, tenantRoleProcedure } from "../_core/trpc";

const managers = ["admin", "manager"] as const;
const readable = ["admin", "manager", "rep", "exec"] as const;
const requiredReason = z.string().trim().min(3).max(3000);
async function siteForTenant(tenantId: string, siteId: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [site] = await db.select().from(inventorySites).where(and(eq(inventorySites.tenantId, tenantId), eq(inventorySites.id, siteId), eq(inventorySites.status, "active"))).limit(1); if (!site) throw new Error("Active inventory site not found in the tenant"); return site; }
async function evidence(scope: ReturnType<typeof resolveTenantScope>, entityType: string, entityId: string, eventType: string, operation: "create" | "status_change", value: unknown, reason: string) { await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType, entityId, eventType, operation, oldValue: null, newValue: value, reason }); }

export const inventoryRouter = router({
  sites: router({
    list: tenantRoleProcedure(readable).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(inventorySites).where(eq(inventorySites.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(inventorySites.updatedAt)); }),
    create: tenantRoleProcedure(managers).input(z.object({ name: z.string().trim().min(2).max(255), code: z.string().trim().toUpperCase().min(2).max(64), siteType: z.enum(["warehouse", "office", "vehicle", "field_stock", "other"]).default("warehouse"), address: z.string().trim().max(3000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(inventorySites).values({ id, tenantId: scope.tenantId, ...input, address: input.address ?? null, createdBy: scope.userId }); await evidence(scope, "inventory_site", id, "inventory.site_created", "create", input, "Inventory site created"); return { id }; }),
  }),
  ledger: router({
    list: tenantRoleProcedure(readable).input(z.object({ siteId: z.string().uuid().optional(), productName: z.string().trim().max(255).optional() }).optional()).query(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; const filters = [eq(inventoryStockLedger.tenantId, scope.tenantId)]; if (input?.siteId) filters.push(eq(inventoryStockLedger.siteId, input.siteId)); if (input?.productName) filters.push(eq(inventoryStockLedger.productName, input.productName)); return db.select().from(inventoryStockLedger).where(and(...filters)).orderBy(desc(inventoryStockLedger.occurredAt)); }),
    record: tenantRoleProcedure(managers).input(z.object({ siteId: z.string().uuid(), productName: z.string().trim().min(1).max(255), lotNumber: z.string().trim().max(128).optional(), expiryDate: z.date().optional(), transactionType: z.enum(["receipt", "issue", "transfer_in", "transfer_out", "return", "adjustment"]), quantityDelta: z.number().finite().refine(value => value !== 0, "Quantity delta cannot be zero"), referenceType: z.string().trim().max(128).optional(), referenceId: z.string().uuid().optional(), reason: requiredReason, occurredAt: z.date().default(() => new Date()) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); await siteForTenant(scope.tenantId, input.siteId); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(inventoryStockLedger).values({ id, tenantId: scope.tenantId, ...input, quantityDelta: String(input.quantityDelta), lotNumber: input.lotNumber ?? null, expiryDate: input.expiryDate ?? null, referenceType: input.referenceType ?? null, referenceId: input.referenceId ?? null, createdBy: scope.userId }); await evidence(scope, "inventory_stock_ledger", id, "inventory.ledger_recorded", "create", input, input.reason); return { id }; }),
    balances: tenantRoleProcedure(readable).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return []; const rows = await db.select().from(inventoryStockLedger).where(eq(inventoryStockLedger.tenantId, scope.tenantId)); const balances = new Map<string, { siteId: string; productName: string; lotNumber: string | null; expiryDate: Date | null; quantity: number }>(); rows.forEach(row => { const key = [row.siteId, row.productName, row.lotNumber ?? "", row.expiryDate?.toISOString() ?? ""].join("|"); const current = balances.get(key) ?? { siteId: row.siteId, productName: row.productName, lotNumber: row.lotNumber, expiryDate: row.expiryDate, quantity: 0 }; current.quantity += Number(row.quantityDelta); balances.set(key, current); }); return Array.from(balances.values()).filter(row => row.quantity !== 0); }),
  }),
  reorder: router({
    list: tenantRoleProcedure(readable).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(inventoryReorderLevels).where(and(eq(inventoryReorderLevels.tenantId, resolveTenantScope(ctx.user!).tenantId), eq(inventoryReorderLevels.status, "active"))).orderBy(desc(inventoryReorderLevels.updatedAt)); }),
    set: tenantRoleProcedure(managers).input(z.object({ siteId: z.string().uuid(), productName: z.string().trim().min(1).max(255), minimumQuantity: z.number().nonnegative(), reorderQuantity: z.number().positive() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); await siteForTenant(scope.tenantId, input.siteId); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [existing] = await db.select().from(inventoryReorderLevels).where(and(eq(inventoryReorderLevels.tenantId, scope.tenantId), eq(inventoryReorderLevels.siteId, input.siteId), eq(inventoryReorderLevels.productName, input.productName))).limit(1); if (existing) { await db.update(inventoryReorderLevels).set({ minimumQuantity: String(input.minimumQuantity), reorderQuantity: String(input.reorderQuantity), status: "active" }).where(and(eq(inventoryReorderLevels.id, existing.id), eq(inventoryReorderLevels.tenantId, scope.tenantId))); await evidence(scope, "inventory_reorder_level", existing.id, "inventory.reorder_updated", "status_change", input, "Inventory reorder level updated"); return { id: existing.id }; } const id = randomUUID(); await db.insert(inventoryReorderLevels).values({ id, tenantId: scope.tenantId, siteId: input.siteId, productName: input.productName, minimumQuantity: String(input.minimumQuantity), reorderQuantity: String(input.reorderQuantity), createdBy: scope.userId }); await evidence(scope, "inventory_reorder_level", id, "inventory.reorder_created", "create", input, "Inventory reorder level created"); return { id }; }),
  }),
});
