import { randomUUID } from "crypto";
import { and, count, desc, eq, inArray, sql } from "drizzle-orm";
import { z } from "zod";
import { accounts, approvedContent, audienceSegments, campaignDeliveries, contacts, contentUsageEvents, marketingCampaigns, plannedVisits } from "../../drizzle/schema";
import { appendAuditEvent, getDb } from "../db";
import { resolveTenantScope } from "../security/access";
import { storagePut } from "../storage";
import { channelConfiguration, dispatchCampaignDelivery } from "../services/campaignDelivery";
import { router, tenantRoleProcedure } from "../_core/trpc";

const managerRoles = ["admin", "manager"] as const;
const readerRoles = ["admin", "manager", "rep", "exec"] as const;
const eventTypes = ["presented", "opened", "completed"] as const;
const assetDataUrl = z.string().regex(/^data:(application\/pdf|image\/(png|jpeg|webp)|video\/mp4);base64,/).max(14 * 1024 * 1024).optional();
const selectorInput = z.object({ accountTypes: z.array(z.enum(["hcp", "pharmacy", "hospital", "distributor", "organization"])).default([]), specialties: z.array(z.string().trim().min(1).max(160)).default([]), tiers: z.array(z.enum(["a", "b", "c", "unclassified"])).default([]), territoryIds: z.array(z.string().uuid()).default([]) });

function decodeAsset(value: string) { const [header, encoded] = value.split(",", 2); const mime = header.match(/^data:(application\/pdf|image\/(?:png|jpeg|webp)|video\/mp4);base64$/)?.[1]; if (!mime || !encoded) throw new Error("Unsupported content asset"); const buffer = Buffer.from(encoded, "base64"); if (buffer.byteLength > 10 * 1024 * 1024) throw new Error("Approved content assets must be 10 MB or smaller"); const extension = mime === "application/pdf" ? "pdf" : mime === "video/mp4" ? "mp4" : mime === "image/jpeg" ? "jpg" : mime.split("/")[1]!; return { mime, buffer, extension }; }

function segmentWhere(tenantId: string, selector: z.infer<typeof selectorInput>) { return and(eq(accounts.tenantId, tenantId), eq(accounts.status, "active"), ...(selector.accountTypes.length ? [inArray(accounts.accountType, selector.accountTypes)] : []), ...(selector.specialties.length ? [inArray(accounts.specialty, selector.specialties)] : []), ...(selector.tiers.length ? [inArray(accounts.tier, selector.tiers)] : []), ...(selector.territoryIds.length ? [inArray(accounts.territoryId, selector.territoryIds)] : [])); }

async function scopedRow<T extends { tenantId: string }>(table: any, tenantId: string, id: string, label: string): Promise<T> { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [row] = await db.select().from(table).where(and(eq(table.tenantId, tenantId), eq(table.id, id))).limit(1); if (!row) throw new Error(`${label} was not found in the active tenant`); return row as T; }

export const marketingRouter = router({
  segments: router({
    list: tenantRoleProcedure(managerRoles).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(audienceSegments).where(eq(audienceSegments.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(audienceSegments.updatedAt)); }),
    create: tenantRoleProcedure(managerRoles).input(z.object({ name: z.string().trim().min(2).max(255), description: z.string().max(3000).optional(), selector: selectorInput })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(audienceSegments).values({ id, tenantId: scope.tenantId, name: input.name, description: input.description ?? null, accountTypes: input.selector.accountTypes, specialties: input.selector.specialties, tiers: input.selector.tiers, territoryIds: input.selector.territoryIds, createdBy: scope.userId }); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "audience_segment", entityId: id, eventType: "marketing.segment_created", operation: "create", oldValue: null, newValue: input, reason: "CRM attribute-based audience segment created" }); return { id }; }),
    activate: tenantRoleProcedure(managerRoles).input(z.object({ id: z.string().uuid(), status: z.enum(["active", "archived"]) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const segment = await scopedRow<typeof audienceSegments.$inferSelect>(audienceSegments, scope.tenantId, input.id, "Audience segment"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(audienceSegments).set({ status: input.status }).where(and(eq(audienceSegments.id, input.id), eq(audienceSegments.tenantId, scope.tenantId))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "audience_segment", entityId: input.id, eventType: `marketing.segment_${input.status}`, operation: "status_change", oldValue: { status: segment.status }, newValue: { status: input.status }, reason: "Marketing audience lifecycle update" }); return { success: true }; }),
    preview: tenantRoleProcedure(managerRoles).input(selectorInput).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return []; const scope = resolveTenantScope(ctx.user!); return db.select().from(accounts).where(segmentWhere(scope.tenantId, input)).orderBy(desc(accounts.updatedAt)); }),
  }),
  content: router({
    list: tenantRoleProcedure(readerRoles).input(z.object({ includeUnapproved: z.boolean().optional() }).optional()).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return []; const scope = resolveTenantScope(ctx.user!); const canManage = managerRoles.includes(scope.role as typeof managerRoles[number]); return db.select().from(approvedContent).where(and(eq(approvedContent.tenantId, scope.tenantId), ...(canManage && input?.includeUnapproved ? [] : [eq(approvedContent.status, "approved")]))).orderBy(desc(approvedContent.updatedAt)); }),
    create: tenantRoleProcedure(managerRoles).input(z.object({ title: z.string().trim().min(2).max(255), description: z.string().max(3000).optional(), contentType: z.enum(["pdf", "image", "video", "html", "link"]), body: z.string().max(12000).optional(), version: z.string().trim().min(1).max(64).default("1.0"), assetDataUrl })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); if ((input.contentType === "html" || input.contentType === "link") && !input.body) throw new Error("HTML or linked content needs a content body or URL"); if (["pdf", "image", "video"].includes(input.contentType) && !input.assetDataUrl) throw new Error("PDF, image, and video content requires an approved asset upload"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); let asset: { key: string; url: string; mime: string } | null = null; if (input.assetDataUrl) { const decoded = decodeAsset(input.assetDataUrl); const stored = await storagePut(`${scope.tenantId}/clm/${id}/asset.${decoded.extension}`, decoded.buffer, decoded.mime); asset = { ...stored, mime: decoded.mime }; } await db.insert(approvedContent).values({ id, tenantId: scope.tenantId, title: input.title, description: input.description ?? null, contentType: input.contentType, body: input.body ?? null, assetKey: asset?.key ?? null, assetUrl: asset?.url ?? null, assetMimeType: asset?.mime ?? null, version: input.version, createdBy: scope.userId }); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "approved_content", entityId: id, eventType: "content.drafted", operation: "create", oldValue: null, newValue: { title: input.title, contentType: input.contentType, version: input.version, hasAsset: !!asset }, reason: "Approved-content library item created for review" }); return { id, assetUrl: asset?.url ?? null }; }),
    review: tenantRoleProcedure(managerRoles).input(z.object({ id: z.string().uuid(), status: z.enum(["approved", "rejected", "retired"]), note: z.string().max(3000).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const content = await scopedRow<typeof approvedContent.$inferSelect>(approvedContent, scope.tenantId, input.id, "Content item"); if (content.status === "retired") throw new Error("Retired content cannot be modified"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const changes = { status: input.status, approvalNote: input.note ?? null, approvedBy: input.status === "approved" ? scope.userId : null, approvedAt: input.status === "approved" ? new Date() : null }; await db.update(approvedContent).set(changes).where(and(eq(approvedContent.id, input.id), eq(approvedContent.tenantId, scope.tenantId))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "approved_content", entityId: input.id, eventType: `content.${input.status}`, operation: "status_change", oldValue: { status: content.status }, newValue: changes, reason: "Approved-content review decision" }); return { success: true }; }),
  }),
  campaigns: router({
    list: tenantRoleProcedure(readerRoles).query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(marketingCampaigns).where(eq(marketingCampaigns.tenantId, resolveTenantScope(ctx.user!).tenantId)).orderBy(desc(marketingCampaigns.updatedAt)); }),
    create: tenantRoleProcedure(managerRoles).input(z.object({ name: z.string().trim().min(2).max(255), segmentId: z.string().uuid().optional(), contentId: z.string().uuid().optional(), channel: z.enum(["email", "sms", "whatsapp"]), subject: z.string().trim().max(255).optional(), messageBody: z.string().trim().min(1).max(12000), whatsappTemplateName: z.string().trim().max(255).optional(), scheduledAt: z.date().optional() }).superRefine((value, ctx) => { if (value.channel === "email" && !value.subject) ctx.addIssue({ code: "custom", message: "Email campaigns require a subject" }); if (value.channel === "whatsapp" && !value.whatsappTemplateName) ctx.addIssue({ code: "custom", message: "WhatsApp campaigns require an approved template name" }); })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); if (input.segmentId) await scopedRow<typeof audienceSegments.$inferSelect>(audienceSegments, scope.tenantId, input.segmentId, "Audience segment"); if (input.contentId) { const content = await scopedRow<typeof approvedContent.$inferSelect>(approvedContent, scope.tenantId, input.contentId, "Content item"); if (content.status !== "approved") throw new Error("Only approved CLM content can be attached to a campaign"); } const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(marketingCampaigns).values({ id, tenantId: scope.tenantId, ...input, segmentId: input.segmentId ?? null, contentId: input.contentId ?? null, subject: input.subject ?? null, whatsappTemplateName: input.whatsappTemplateName ?? null, scheduledAt: input.scheduledAt ?? null, createdBy: scope.userId }); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "marketing_campaign", entityId: id, eventType: "campaign.drafted", operation: "create", oldValue: null, newValue: { name: input.name, channel: input.channel, segmentId: input.segmentId ?? null, contentId: input.contentId ?? null }, reason: "Marketing campaign drafted" }); return { id }; }),
    review: tenantRoleProcedure(managerRoles).input(z.object({ id: z.string().uuid(), status: z.enum(["approved", "paused", "cancelled"]) })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const campaign = await scopedRow<typeof marketingCampaigns.$inferSelect>(marketingCampaigns, scope.tenantId, input.id, "Campaign"); if (campaign.status === "completed" || campaign.status === "cancelled") throw new Error("Campaign lifecycle is closed"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const changes = { status: input.status, approvedBy: input.status === "approved" ? scope.userId : campaign.approvedBy, approvedAt: input.status === "approved" ? new Date() : campaign.approvedAt }; await db.update(marketingCampaigns).set(changes).where(and(eq(marketingCampaigns.id, input.id), eq(marketingCampaigns.tenantId, scope.tenantId))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "marketing_campaign", entityId: input.id, eventType: `campaign.${input.status}`, operation: "status_change", oldValue: { status: campaign.status }, newValue: changes, reason: "Campaign approval lifecycle" }); return { success: true }; }),
    queue: tenantRoleProcedure(managerRoles).input(z.object({ id: z.string().uuid() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const campaign = await scopedRow<typeof marketingCampaigns.$inferSelect>(marketingCampaigns, scope.tenantId, input.id, "Campaign"); if (campaign.status !== "approved") throw new Error("Only approved campaigns can be queued for delivery"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const segment = campaign.segmentId ? await scopedRow<typeof audienceSegments.$inferSelect>(audienceSegments, scope.tenantId, campaign.segmentId, "Audience segment") : null; if (segment && segment.status !== "active") throw new Error("Campaign audience segment must be active"); const selector = { accountTypes: (segment?.accountTypes ?? []) as any[], specialties: (segment?.specialties ?? []) as string[], tiers: (segment?.tiers ?? []) as any[], territoryIds: (segment?.territoryIds ?? []) as string[] }; const recipients = await db.select({ contactId: contacts.id, accountId: accounts.id, email: contacts.email, phone: contacts.phone }).from(contacts).innerJoin(accounts, eq(contacts.accountId, accounts.id)).where(and(segmentWhere(scope.tenantId, selector as z.infer<typeof selectorInput>), eq(contacts.tenantId, scope.tenantId), eq(contacts.status, "active"))); const usable = recipients.filter(contact => campaign.channel === "email" ? !!contact.email : !!contact.phone); const existing = await db.select().from(campaignDeliveries).where(and(eq(campaignDeliveries.tenantId, scope.tenantId), eq(campaignDeliveries.campaignId, campaign.id))); const deliveredContacts = new Set(existing.map(item => item.contactId)); const pending = usable.filter(contact => !deliveredContacts.has(contact.contactId)); if (pending.length) await db.insert(campaignDeliveries).values(pending.map(contact => ({ id: randomUUID(), tenantId: scope.tenantId, campaignId: campaign.id, accountId: contact.accountId, contactId: contact.contactId, channel: campaign.channel, recipient: campaign.channel === "email" ? contact.email! : contact.phone!, payloadSnapshot: { subject: campaign.subject, messageBody: campaign.messageBody, whatsappTemplateName: campaign.whatsappTemplateName, contentId: campaign.contentId }, createdBy: scope.userId }))); await db.update(marketingCampaigns).set({ status: "queued" }).where(and(eq(marketingCampaigns.id, campaign.id), eq(marketingCampaigns.tenantId, scope.tenantId))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "marketing_campaign", entityId: campaign.id, eventType: "campaign.queued", operation: "status_change", oldValue: { status: campaign.status }, newValue: { status: "queued", deliveryCount: pending.length, skippedExisting: usable.length - pending.length }, reason: "Approved campaign staged for configured delivery channel" }); return { queued: pending.length, skippedExisting: usable.length - pending.length }; }),
    channelStatus: tenantRoleProcedure(managerRoles).query(() => ({ email: channelConfiguration("email"), sms: channelConfiguration("sms"), whatsapp: channelConfiguration("whatsapp") })),
    dispatch: tenantRoleProcedure(managerRoles).input(z.object({ id: z.string().uuid() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const campaign = await scopedRow<typeof marketingCampaigns.$inferSelect>(marketingCampaigns, scope.tenantId, input.id, "Campaign"); if (campaign.status !== "queued") throw new Error("Only queued campaigns can be dispatched"); const configuration = channelConfiguration(campaign.channel); if (!configuration.configured) throw new Error(`The ${campaign.channel} channel is not configured: ${configuration.missing.join(", ")}`); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const pending = await db.select().from(campaignDeliveries).where(and(eq(campaignDeliveries.tenantId, scope.tenantId), eq(campaignDeliveries.campaignId, campaign.id), eq(campaignDeliveries.status, "queued"))); let sent = 0, failed = 0; await db.update(marketingCampaigns).set({ status: "sending" }).where(and(eq(marketingCampaigns.id, campaign.id), eq(marketingCampaigns.tenantId, scope.tenantId))); for (const delivery of pending) { const snapshot = delivery.payloadSnapshot as { subject?: string | null; messageBody: string; whatsappTemplateName?: string | null }; const result = await dispatchCampaignDelivery(campaign.channel, { campaignId: campaign.id, deliveryId: delivery.id, recipient: delivery.recipient, ...snapshot }); if (result.status === "sent") sent += 1; else failed += 1; await db.update(campaignDeliveries).set({ status: result.status, providerMessageId: result.providerMessageId ?? null, failureReason: result.failureReason ?? null }).where(and(eq(campaignDeliveries.id, delivery.id), eq(campaignDeliveries.tenantId, scope.tenantId))); } await db.update(marketingCampaigns).set({ status: "completed" }).where(and(eq(marketingCampaigns.id, campaign.id), eq(marketingCampaigns.tenantId, scope.tenantId))); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "marketing_campaign", entityId: campaign.id, eventType: "campaign.dispatched", operation: "status_change", oldValue: { status: "queued" }, newValue: { status: "completed", sent, failed }, reason: "Authorized marketing campaign delivery dispatch" }); return { sent, failed }; }),
  }),
  usage: router({
    record: tenantRoleProcedure(["admin", "manager", "rep"] as const).input(z.object({ contentId: z.string().uuid(), accountId: z.string().uuid(), campaignId: z.string().uuid().optional(), plannedVisitId: z.string().uuid().optional(), eventType: z.enum(eventTypes), occurredAt: z.date(), durationSeconds: z.number().int().nonnegative().max(14400).optional() })).mutation(async ({ ctx, input }) => { const scope = resolveTenantScope(ctx.user!); const content = await scopedRow<typeof approvedContent.$inferSelect>(approvedContent, scope.tenantId, input.contentId, "Content item"); if (content.status !== "approved") throw new Error("Only approved content can be presented to an account"); await scopedRow<typeof accounts.$inferSelect>(accounts, scope.tenantId, input.accountId, "Account"); if (input.campaignId) await scopedRow<typeof marketingCampaigns.$inferSelect>(marketingCampaigns, scope.tenantId, input.campaignId, "Campaign"); if (input.plannedVisitId) { const visit = await scopedRow<typeof plannedVisits.$inferSelect>(plannedVisits, scope.tenantId, input.plannedVisitId, "Planned visit"); if (visit.accountId !== input.accountId) throw new Error("Content usage account must match the selected planned visit"); } const db = await getDb(); if (!db) throw new Error("Database unavailable"); const id = randomUUID(); await db.insert(contentUsageEvents).values({ id, tenantId: scope.tenantId, contentId: input.contentId, accountId: input.accountId, repUserId: scope.userId, campaignId: input.campaignId ?? null, plannedVisitId: input.plannedVisitId ?? null, eventType: input.eventType, occurredAt: input.occurredAt, durationSeconds: input.durationSeconds ?? null, createdBy: scope.userId }); await appendAuditEvent({ tenantId: scope.tenantId, actorUserId: scope.userId, entityType: "content_usage_event", entityId: id, eventType: `content.${input.eventType}`, operation: "create", oldValue: null, newValue: input, reason: "Approved content presentation evidence" }); return { id }; }),
    analytics: tenantRoleProcedure(["admin", "manager", "exec"] as const).query(async ({ ctx }) => { const scope = resolveTenantScope(ctx.user!); const db = await getDb(); if (!db) return { totals: { presentations: 0, accountsReached: 0 }, byContent: [] as Array<{ contentId: string; title: string; presentations: number }> }; const [presentations] = await db.select({ value: count(contentUsageEvents.id) }).from(contentUsageEvents).where(and(eq(contentUsageEvents.tenantId, scope.tenantId), eq(contentUsageEvents.eventType, "presented"))); const [accountsReached] = await db.select({ value: sql<number>`count(distinct ${contentUsageEvents.accountId})` }).from(contentUsageEvents).where(and(eq(contentUsageEvents.tenantId, scope.tenantId), eq(contentUsageEvents.eventType, "presented"))); const byContent = await db.select({ contentId: approvedContent.id, title: approvedContent.title, presentations: count(contentUsageEvents.id) }).from(contentUsageEvents).innerJoin(approvedContent, eq(contentUsageEvents.contentId, approvedContent.id)).where(and(eq(contentUsageEvents.tenantId, scope.tenantId), eq(contentUsageEvents.eventType, "presented"))).groupBy(approvedContent.id, approvedContent.title).orderBy(desc(count(contentUsageEvents.id))); return { totals: { presentations: presentations?.value ?? 0, accountsReached: Number(accountsReached?.value ?? 0) }, byContent }; }),
  }),
});
