import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ClipboardList, FileSignature, PackageCheck } from "lucide-react";
import { AccessDenied } from "./Tenants";

type RegistryKind = "visits" | "samples" | "signatures";
type VisitRow = { id: string; accountName: string; objective: string; repUserId: number; occurredAt: Date; status: string };
type SampleRow = { id: string; productName: string; lotNumber: string; transactionType: string; quantity: string; expiryDate: Date; status: string };
type SignatureRow = { id: string; subjectType: string; subjectId: string; signerUserId: number; meaning: string; signedAt: Date; status: string };
const config = { visits: { eyebrow: "Immutable field evidence", title: "Visit logs", description: "Visit entries are inserted as regulated evidence. Corrections require a new superseding entry rather than editing history.", icon: ClipboardList }, samples: { eyebrow: "Chain of custody", title: "Sample transactions", description: "Allocation, hand-off, returns, and adjustments are immutable transactions tied to lot and expiry data.", icon: PackageCheck }, signatures: { eyebrow: "Electronic records", title: "E-signatures", description: "Signature meaning, signer, subject reference, and intent are preserved in append-only evidence.", icon: FileSignature } };
export default function ComplianceRegistry({ kind }: { kind: RegistryKind }) {
  const { user } = useAuth(); const allowed = !!user && ["admin", "manager", "exec"].includes(user.role); const item = config[kind];
  const visits = trpc.compliance.visits.list.useQuery(undefined, { enabled: allowed && kind === "visits" });
  const samples = trpc.compliance.samples.list.useQuery(undefined, { enabled: allowed && kind === "samples" });
  const signatures = trpc.compliance.signatures.list.useQuery(undefined, { enabled: allowed && kind === "signatures" });
  if (!allowed) return <AccessDenied />;
  const records = kind === "visits" ? visits.data : kind === "samples" ? samples.data : signatures.data;
  const loading = kind === "visits" ? visits.isLoading : kind === "samples" ? samples.isLoading : signatures.isLoading;
  return <div className="space-y-6"><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e9f8f2] text-[#178066]"><item.icon className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">{item.eyebrow}</p><h2 className="mt-1 text-2xl font-bold tracking-[-.035em]">{item.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{item.description}</p></div></div><Card className="overflow-hidden border-slate-200/80 bg-white"><CardContent className="p-0"><div className="overflow-x-auto">{kind === "visits" ? <VisitTable records={records as VisitRow[] | undefined} loading={loading} /> : kind === "samples" ? <SampleTable records={records as SampleRow[] | undefined} loading={loading} /> : <SignatureTable records={records as SignatureRow[] | undefined} loading={loading} />}</div></CardContent></Card></div>;
}
function TableHead({ children }: { children: React.ReactNode }) { return <thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-[.12em] text-slate-400"><tr>{children}</tr></thead>; }
function Empty({ colSpan, loading, text }: { colSpan: number; loading: boolean; text: string }) { return <tr><td colSpan={colSpan} className="px-6 py-14 text-center text-sm text-slate-400">{loading ? "Reading immutable registry…" : text}</td></tr>; }
function VisitTable({ records, loading }: { records: VisitRow[] | undefined; loading: boolean }) { return <table className="w-full min-w-[760px] text-left"><TableHead><th className="px-6 py-4">Account</th><th className="px-4 py-4">Rep ID</th><th className="px-4 py-4">Occurred</th><th className="px-4 py-4">Status</th><th className="px-6 py-4">Evidence</th></TableHead><tbody className="divide-y divide-slate-100">{!records?.length ? <Empty colSpan={5} loading={loading} text="No visit evidence has been recorded for this tenant." /> : records.map(record => <tr key={record.id}><td className="px-6 py-4"><p className="text-sm font-semibold text-slate-700">{record.accountName}</p><p className="mt-0.5 max-w-[260px] truncate text-xs text-slate-400">{record.objective}</p></td><td className="px-4 py-4 text-sm text-slate-600">{record.repUserId}</td><td className="px-4 py-4 text-sm text-slate-600">{new Date(record.occurredAt).toLocaleString()}</td><td className="px-4 py-4"><ImmutableStatus status={record.status} /></td><td className="px-6 py-4 font-mono text-xs text-slate-400">{record.id.slice(0, 12)}…</td></tr>)}</tbody></table>; }
function SampleTable({ records, loading }: { records: SampleRow[] | undefined; loading: boolean }) { return <table className="w-full min-w-[780px] text-left"><TableHead><th className="px-6 py-4">Product / lot</th><th className="px-4 py-4">Type</th><th className="px-4 py-4">Quantity</th><th className="px-4 py-4">Expiry</th><th className="px-6 py-4">Status</th></TableHead><tbody className="divide-y divide-slate-100">{!records?.length ? <Empty colSpan={5} loading={loading} text="No sample chain-of-custody evidence has been recorded for this tenant." /> : records.map(record => <tr key={record.id}><td className="px-6 py-4"><p className="text-sm font-semibold text-slate-700">{record.productName}</p><p className="mt-0.5 text-xs text-slate-400">Lot {record.lotNumber}</p></td><td className="px-4 py-4 text-sm capitalize text-slate-600">{record.transactionType}</td><td className="px-4 py-4 text-sm text-slate-600">{record.quantity}</td><td className="px-4 py-4 text-sm text-slate-600">{new Date(record.expiryDate).toLocaleDateString()}</td><td className="px-6 py-4"><ImmutableStatus status={record.status} /></td></tr>)}</tbody></table>; }
function SignatureTable({ records, loading }: { records: SignatureRow[] | undefined; loading: boolean }) { return <table className="w-full min-w-[780px] text-left"><TableHead><th className="px-6 py-4">Subject</th><th className="px-4 py-4">Signer</th><th className="px-4 py-4">Meaning</th><th className="px-4 py-4">Signed</th><th className="px-6 py-4">Status</th></TableHead><tbody className="divide-y divide-slate-100">{!records?.length ? <Empty colSpan={5} loading={loading} text="No electronic signatures have been recorded for this tenant." /> : records.map(record => <tr key={record.id}><td className="px-6 py-4"><p className="text-sm font-semibold capitalize text-slate-700">{record.subjectType}</p><p className="mt-0.5 font-mono text-xs text-slate-400">{record.subjectId.slice(0, 12)}…</p></td><td className="px-4 py-4 text-sm text-slate-600">{record.signerUserId}</td><td className="px-4 py-4 text-sm capitalize text-slate-600">{record.meaning}</td><td className="px-4 py-4 text-sm text-slate-600">{new Date(record.signedAt).toLocaleString()}</td><td className="px-6 py-4"><ImmutableStatus status={record.status} /></td></tr>)}</tbody></table>; }
function ImmutableStatus({ status }: { status: string }) { return <Badge className="border-0 bg-[#e9f8f2] capitalize text-[#188064] hover:bg-[#e9f8f2]">{status}</Badge>; }
