import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ClipboardPenLine, ContactRound, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { AccessDenied } from "./Tenants";

const writeRoles = ["admin", "manager"];
const readRoles = ["admin", "manager", "rep", "exec"];

export function ContactsPage() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const accounts = trpc.crm.accounts.list.useQuery(undefined, { enabled: !!user && readRoles.includes(user.role) }); const contacts = trpc.crm.contacts.list.useQuery(undefined, { enabled: !!user && readRoles.includes(user.role) }); const [open, setOpen] = useState(false); const [accountId, setAccountId] = useState(""); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const create = trpc.crm.contacts.create.useMutation({ onSuccess: async () => { setOpen(false); setFirstName(""); setLastName(""); await utils.crm.contacts.list.invalidate(); toast.success("Contact added to the tenant account."); }, onError: e => toast.error(e.message) });
  if (!user || !readRoles.includes(user.role)) return <AccessDenied />;
  const submit = (e: FormEvent) => { e.preventDefault(); create.mutate({ accountId, firstName, lastName }); };
  return <section className="space-y-6"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">Account relationships</p><h2 className="mt-1 text-2xl font-bold">Contacts</h2><p className="mt-2 text-sm text-slate-500">People associated with each HCP, pharmacy, hospital, or B2B organization.</p></div>{writeRoles.includes(user.role)&&<Button onClick={()=>setOpen(!open)} className="bg-[#147d66] hover:bg-[#0f6956]"><Plus className="mr-2 h-4 w-4"/>Add contact</Button>}</div>{open&&<Card><CardContent className="p-5"><form onSubmit={submit} className="grid gap-3 sm:grid-cols-4"><select required value={accountId} onChange={e=>setAccountId(e.target.value)} className="h-10 rounded-md border px-3 text-sm"><option value="">Select account</option>{accounts.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><Input required value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="First name"/><Input required value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Last name"/><Button disabled={create.isPending}>Save contact</Button></form></CardContent></Card>}<Card className="overflow-hidden"><CardContent className="p-0"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="p-4">Contact</th><th className="p-4">Account ID</th><th className="p-4">Channel</th><th className="p-4">Status</th></tr></thead><tbody>{contacts.data?.length?contacts.data.map(c=><tr key={c.id} className="border-t"><td className="p-4 font-semibold">{c.firstName} {c.lastName}<p className="text-xs font-normal text-slate-400">{c.title??c.email??"—"}</p></td><td className="p-4 font-mono text-xs text-slate-500">{c.accountId.slice(0,10)}…</td><td className="p-4 capitalize">{c.preferredChannel.replace("_"," ")}</td><td className="p-4 capitalize text-slate-500">{c.status}</td></tr>):<tr><td colSpan={4} className="p-12 text-center text-sm text-slate-400">No contact relationships recorded.</td></tr>}</tbody></table></CardContent></Card></section>;
}

export function VisitCapturePage() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const accounts = trpc.crm.accounts.list.useQuery(undefined, { enabled: !!user && readRoles.includes(user.role) }); const [accountId, setAccountId] = useState(""); const [objective, setObjective] = useState(""); const [products, setProducts] = useState(""); const [nextSteps, setNextSteps] = useState(""); const create = trpc.compliance.visits.create.useMutation({ onSuccess: async () => { setObjective(""); setProducts(""); setNextSteps(""); await utils.compliance.visits.list.invalidate(); toast.success("Immutable visit evidence recorded."); }, onError: e => toast.error(e.message) }); if (!user || !["admin","manager","rep"].includes(user.role)) return <AccessDenied />;
  const submit=(e:FormEvent)=>{e.preventDefault();const account=accounts.data?.find(a=>a.id===accountId);if(!account){toast.error("Select a tenant account first.");return;}create.mutate({accountId,accountName:account.name,objective,productsDiscussed:products.split(",").map(p=>p.trim()).filter(Boolean),nextSteps:nextSteps||undefined,occurredAt:new Date()});};
  return <section className="space-y-6"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#e9f8f2] text-[#178066]"><ClipboardPenLine className="h-5 w-5"/></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">Immutable field evidence</p><h2 className="mt-1 text-2xl font-bold">Log a completed visit</h2><p className="mt-2 text-sm text-slate-500">Entries are create-only. Corrections are recorded as superseding evidence rather than edits.</p></div></div><Card><CardContent className="p-6"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Account<select required value={accountId} onChange={e=>setAccountId(e.target.value)} className="mt-2 h-10 w-full rounded-md border px-3 font-normal"><option value="">Select account</option>{accounts.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="text-sm font-semibold">Products discussed<Input required className="mt-2" value={products} onChange={e=>setProducts(e.target.value)} placeholder="Product A, Product B"/></label><label className="text-sm font-semibold md:col-span-2">Objective<textarea required value={objective} onChange={e=>setObjective(e.target.value)} className="mt-2 min-h-24 w-full rounded-md border p-3 text-sm font-normal" placeholder="Visit objective and key discussion points"/></label><label className="text-sm font-semibold md:col-span-2">Next steps<textarea value={nextSteps} onChange={e=>setNextSteps(e.target.value)} className="mt-2 min-h-20 w-full rounded-md border p-3 text-sm font-normal" placeholder="Follow-up commitments"/></label><div className="md:col-span-2 flex justify-end"><Button disabled={create.isPending} className="bg-[#147d66] hover:bg-[#0f6956]">{create.isPending?"Recording…":"Record immutable visit"}</Button></div></form></CardContent></Card></section>;
}
