import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { FormEvent, useState } from "react";
import { useRoute } from "wouter";
import { toast } from "sonner";
import { AccessDenied } from "./Tenants";

const managers=["admin","manager"];
export function TerritoryManager(){const{user}=useAuth();const utils=trpc.useUtils();const [name,setName]=useState("");const [code,setCode]=useState("");const list=trpc.crm.territories.list.useQuery(undefined,{enabled:!!user&&managers.includes(user.role)});const create=trpc.crm.territories.create.useMutation({onSuccess:async()=>{setName("");setCode("");await utils.crm.territories.list.invalidate();toast.success("Territory created.")}});if(!user||!managers.includes(user.role))return <AccessDenied/>;return <section className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">Field force design</p><h2 className="mt-1 text-2xl font-bold">Territory management</h2></div><Card><CardContent className="p-5"><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate({name,code})}} className="flex gap-3"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Territory name"/><Input required value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Code"/><Button>Create territory</Button></form></CardContent></Card><div className="grid gap-3 md:grid-cols-3">{list.data?.map(t=><Card key={t.id}><CardContent className="p-4"><p className="font-bold">{t.name}</p><p className="mt-1 text-xs text-slate-500">{t.code} · {t.status}</p></CardContent></Card>)}</div></section>}
export function CyclePlanner(){const{user}=useAuth();const utils=trpc.useUtils();const [name,setName]=useState("");const [startDate,setStartDate]=useState("");const [endDate,setEndDate]=useState("");const list=trpc.crm.plans.list.useQuery(undefined,{enabled:!!user&&managers.includes(user.role)});const create=trpc.crm.plans.create.useMutation({onSuccess:async()=>{setName("");await utils.crm.plans.list.invalidate();toast.success("Cycle plan created.")},onError:e=>toast.error(e.message)});if(!user||!managers.includes(user.role))return <AccessDenied/>;return <section className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">Call planning</p><h2 className="mt-1 text-2xl font-bold">Cycle planner</h2></div><Card><CardContent className="p-5"><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate({name,startDate:new Date(`${startDate}T00:00:00Z`),endDate:new Date(`${endDate}T00:00:00Z`)})}} className="grid gap-3 md:grid-cols-4"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Plan name"/><Input required type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/><Input required type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/><Button>Create cycle plan</Button></form></CardContent></Card><div className="space-y-3">{list.data?.map(p=><Card key={p.id}><CardContent className="p-4"><p className="font-bold">{p.name}</p><p className="mt-1 text-sm capitalize text-slate-500">{p.status} · {new Date(p.startDate).toLocaleDateString()}–{new Date(p.endDate).toLocaleDateString()}</p></CardContent></Card>)}</div></section>}
export function AccountDetail(){const[,params]=useRoute("/crm/accounts/:id");const{user}=useAuth();const accounts=trpc.crm.accounts.list.useQuery(undefined,{enabled:!!user});const contacts=trpc.crm.contacts.list.useQuery({accountId:params?.id??"00000000-0000-4000-8000-000000000000"},{enabled:!!user&&!!params?.id});if(!user||!["admin","manager","rep","exec"].includes(user.role))return <AccessDenied/>;const account=accounts.data?.find(a=>a.id===params?.id);return <section className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">Account 360</p><h2 className="mt-1 text-2xl font-bold">{account?.name??"Account detail"}</h2><p className="mt-2 text-sm text-slate-500">{account?.accountType} · {account?.specialty??"No specialty recorded"}</p></div><Card><CardContent className="p-5"><h3 className="font-bold">Associated contacts</h3><div className="mt-4 space-y-2">{contacts.data?.map(c=><div key={c.id} className="rounded-lg bg-slate-50 p-3 text-sm">{c.firstName} {c.lastName} <span className="text-slate-400">{c.email??""}</span></div>)||<p className="text-sm text-slate-400">No contacts.</p>}</div></CardContent></Card></section>}
