import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { UserRoundCheck } from "lucide-react";
import { toast } from "sonner";
import { AccessDenied } from "./Tenants";

const viewRoles = ["admin", "manager", "hr", "exec"];
export default function DirectoryPage() {
  const { user } = useAuth(); const utils = trpc.useUtils();
  const query = trpc.directory.list.useQuery(undefined, { enabled: !!user && viewRoles.includes(user.role) });
  const change = trpc.directory.changeStatus.useMutation({ onSuccess: async () => { toast.success("Employee lifecycle status changed and audit evidence recorded."); await utils.directory.list.invalidate(); }, onError: error => toast.error(error.message) });
  if (!user || !viewRoles.includes(user.role)) return <AccessDenied />;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">Tenant-scoped workforce</p><h2 className="mt-2 text-2xl font-bold tracking-[-.035em]">Employee directory</h2><p className="mt-2 text-sm leading-6 text-slate-500">Every employee identity is scoped to the active tenant and retains creation metadata. Status transitions are logged rather than deleted.</p></div><Card className="overflow-hidden border-slate-200/80 bg-white"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-[.12em] text-slate-400"><tr><th className="px-6 py-4">Employee</th><th className="px-4 py-4">Role</th><th className="px-4 py-4">Department</th><th className="px-4 py-4">Territory</th><th className="px-4 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{query.isLoading && <tr><td colSpan={6} className="px-6 py-12 text-center text-sm text-slate-400">Reading tenant directory…</td></tr>}{!query.isLoading && query.data?.length === 0 && <tr><td colSpan={6} className="px-6 py-14 text-center"><UserRoundCheck className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3 text-sm font-semibold text-slate-600">No active workforce records</p><p className="mt-1 text-xs text-slate-400">Tenant administrators can add employee onboarding in the next workforce module increment.</p></td></tr>}{query.data?.map(employee => <tr key={employee.id} className="hover:bg-slate-50/60"><td className="px-6 py-4"><p className="text-sm font-semibold text-slate-700">{employee.name ?? "Unnamed employee"}</p><p className="mt-0.5 text-xs text-slate-400">{employee.email}</p></td><td className="px-4 py-4"><Badge className="border-0 bg-[#eef2ff] text-[#5662c5] capitalize hover:bg-[#eef2ff]">{employee.role.replace("_", " ")}</Badge></td><td className="px-4 py-4 text-sm text-slate-600">{employee.department ?? "—"}</td><td className="px-4 py-4 text-sm text-slate-600">{employee.territory ?? "—"}</td><td className="px-4 py-4"><Badge className={`border-0 capitalize ${employee.status === "active" ? "bg-[#e9f8f2] text-[#188064]" : "bg-[#fff1ef] text-[#bf544b]"}`}>{employee.status}</Badge></td><td className="px-6 py-4 text-right">{["admin", "hr"].includes(user.role) && employee.id !== user.id && <Button size="sm" variant="outline" className="h-8 text-xs" disabled={change.isPending} onClick={() => change.mutate({ userId: employee.id, status: employee.status === "active" ? "suspended" : "active", reason: `Lifecycle policy status changed to ${employee.status === "active" ? "suspended" : "active"}.` })}>{employee.status === "active" ? "Suspend" : "Activate"}</Button>}</td></tr>)}</tbody></table></div></CardContent></Card></div>;
}
