import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Cable, Copy, KeyRound, PauseCircle, PlayCircle, Send, ShieldCheck, Webhook } from "lucide-react";
import { useState } from "react";

const events = ["inventory.stock_movement", "procurement.request_submitted", "document.activated", "coaching.scorecard_created"] as const;
const scopeLabels = { "crm.read": "CRM read", "inventory.read": "Inventory read", "documents.read": "Documents read", "webhooks.manage": "Webhook management" } as const;

export default function IntegrationsPage() {
  const { user } = useAuth(); const canManage = user?.role === "admin"; const utils = trpc.useUtils();
  const keys = trpc.integrations.apiKeys.list.useQuery(undefined, { enabled: canManage }); const endpoints = trpc.integrations.webhooks.list.useQuery(undefined, { enabled: canManage }); const deliveries = trpc.integrations.webhooks.deliveries.useQuery(undefined, { enabled: canManage });
  const [keyLabel, setKeyLabel] = useState(""); const [keyScope, setKeyScope] = useState<keyof typeof scopeLabels>("crm.read"); const [issued, setIssued] = useState<string | null>(null); const [webhook, setWebhook] = useState({ name: "", endpointUrl: "", eventType: events[0] }); const refresh = () => Promise.all([utils.integrations.apiKeys.list.invalidate(), utils.integrations.webhooks.list.invalidate(), utils.integrations.webhooks.deliveries.invalidate()]);
  const issue = trpc.integrations.apiKeys.issue.useMutation({ onSuccess: result => { setIssued(result.apiKey); setKeyLabel(""); refresh(); } }); const revokeKey = trpc.integrations.apiKeys.revoke.useMutation({ onSuccess: refresh }); const register = trpc.integrations.webhooks.register.useMutation({ onSuccess: () => { setWebhook({ name: "", endpointUrl: "", eventType: events[0] }); refresh(); } }); const setStatus = trpc.integrations.webhooks.setStatus.useMutation({ onSuccess: refresh }); const dispatch = trpc.integrations.webhooks.dispatchTest.useMutation({ onSuccess: refresh });
  if (!canManage) return <Card><CardContent className="p-10 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-slate-400" /><h2 className="mt-4 text-xl font-bold">Integration administration is restricted</h2><p className="mt-2 text-sm text-slate-500">Only tenant administrators can issue API credentials or enable outbound webhooks.</p></CardContent></Card>;
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#178066]">Self-hosted gateway</p><h2 className="mt-2 text-3xl font-bold tracking-[-.04em] text-[#172033]">Integrations</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Versioned tenant API keys are stored only as hashes. Webhooks are limited to public HTTPS endpoints and every delivery retains a compact audit record without raw payload data.</p></div>
    {issued && <Card className="border-amber-200 bg-amber-50"><CardContent className="p-5"><div className="flex items-start gap-3"><KeyRound className="mt-0.5 h-5 w-5 text-amber-700" /><div className="min-w-0 flex-1"><p className="font-semibold text-amber-950">Copy this API key now</p><p className="mt-1 text-sm text-amber-900">The raw key is shown once and cannot be recovered after this screen is dismissed.</p><code className="mt-3 block break-all rounded-xl border border-amber-200 bg-white px-3 py-2 text-xs text-slate-800">{issued}</code></div><Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(issued)}><Copy className="h-4 w-4" /></Button></div></CardContent></Card>}
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-emerald-600" />Issue v1 API key</CardTitle></CardHeader><CardContent className="space-y-3"><div className="space-y-1.5"><Label>Key label</Label><Input placeholder="Reporting connector" value={keyLabel} onChange={event => setKeyLabel(event.target.value)} /></div><div className="space-y-1.5"><Label>Scope</Label><Select value={keyScope} onValueChange={value => setKeyScope(value as keyof typeof scopeLabels)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(scopeLabels).map(([scope, label]) => <SelectItem key={scope} value={scope}>{label}</SelectItem>)}</SelectContent></Select></div><Button className="w-full" disabled={keyLabel.trim().length < 2 || issue.isPending} onClick={() => issue.mutate({ label: keyLabel, scopes: [keyScope] })}>Issue key once</Button></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Webhook className="h-5 w-5 text-emerald-600" />Register outbound webhook</CardTitle></CardHeader><CardContent className="space-y-3"><div className="space-y-1.5"><Label>Name</Label><Input placeholder="ERP synchronization" value={webhook.name} onChange={event => setWebhook(current => ({ ...current, name: event.target.value }))} /></div><div className="space-y-1.5"><Label>Public HTTPS URL</Label><Input placeholder="https://integration.example.org/events" value={webhook.endpointUrl} onChange={event => setWebhook(current => ({ ...current, endpointUrl: event.target.value }))} /></div><div className="space-y-1.5"><Label>Allowed test event</Label><Select value={webhook.eventType} onValueChange={eventType => setWebhook(current => ({ ...current, eventType: eventType as typeof current.eventType }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{events.map(event => <SelectItem key={event} value={event}>{event}</SelectItem>)}</SelectContent></Select></div><Button className="w-full" disabled={webhook.name.trim().length < 2 || !webhook.endpointUrl || register.isPending} onClick={() => register.mutate({ name: webhook.name, endpointUrl: webhook.endpointUrl, eventTypes: [webhook.eventType] })}>Register controlled endpoint</Button></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Cable className="h-5 w-5 text-emerald-600" />Versioned API credentials</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Label</th><th className="pb-3">Prefix</th><th className="pb-3">Scopes</th><th className="pb-3">Version</th><th className="pb-3">Status</th><th className="pb-3">Action</th></tr></thead><tbody>{(keys.data ?? []).map(key => <tr key={key.id} className="border-b last:border-0"><td className="py-4 font-medium">{key.label}</td><td className="py-4 font-mono text-xs text-slate-600">{key.keyPrefix}…</td><td className="py-4 text-slate-500">{(key.scopes as string[]).join(", ")}</td><td className="py-4">{key.apiVersion}</td><td className="py-4"><Badge variant={key.status === "active" ? "secondary" : "outline"}>{key.status}</Badge></td><td className="py-4">{key.status === "active" && <Button size="sm" variant="outline" onClick={() => revokeKey.mutate({ id: key.id, reason: "Administrator revoked integration key" })}>Revoke</Button>}</td></tr>)}{!keys.data?.length && <tr><td colSpan={6} className="py-10 text-center text-slate-500">No integration API keys have been issued.</td></tr>}</tbody></table></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Send className="h-5 w-5 text-emerald-600" />Controlled webhook endpoints</CardTitle></CardHeader><CardContent className="space-y-3">{(endpoints.data ?? []).map(endpoint => <div key={endpoint.id} className="flex flex-col justify-between gap-3 rounded-2xl border border-slate-200 p-4 lg:flex-row lg:items-center"><div><p className="font-semibold">{endpoint.name} <Badge className="ml-2" variant={endpoint.status === "active" ? "secondary" : "outline"}>{endpoint.status}</Badge></p><p className="mt-1 break-all text-xs text-slate-500">{endpoint.endpointUrl}</p><p className="mt-2 text-xs text-slate-500">v{endpoint.payloadVersion} · {(endpoint.eventTypes as string[]).join(", ")}</p></div><div className="flex gap-2">{endpoint.status === "active" ? <Button size="sm" variant="outline" onClick={() => setStatus.mutate({ id: endpoint.id, status: "paused", reason: "Administrator paused webhook" })}><PauseCircle className="mr-1 h-4 w-4" />Pause</Button> : endpoint.status === "paused" ? <Button size="sm" variant="outline" onClick={() => setStatus.mutate({ id: endpoint.id, status: "active", reason: "Administrator reactivated webhook" })}><PlayCircle className="mr-1 h-4 w-4" />Resume</Button> : null}{endpoint.status === "active" && <Button size="sm" onClick={() => dispatch.mutate({ id: endpoint.id, eventType: (endpoint.eventTypes as typeof events)[0] })}>Test delivery</Button>}</div></div>)}{!endpoints.data?.length && <p className="py-8 text-center text-sm text-slate-500">No outbound webhook endpoints are enabled.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Latest delivery evidence</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Event</th><th className="pb-3">Status</th><th className="pb-3">HTTP</th><th className="pb-3">Duration</th><th className="pb-3">Evidence hash</th></tr></thead><tbody>{(deliveries.data ?? []).map(row => <tr key={row.id} className="border-b last:border-0"><td className="py-4">{row.eventType}</td><td className="py-4"><Badge variant={row.deliveryStatus === "delivered" ? "secondary" : "outline"}>{row.deliveryStatus}</Badge></td><td className="py-4">{row.httpStatus ?? "—"}</td><td className="py-4">{row.durationMs} ms</td><td className="py-4 font-mono text-xs text-slate-500">{row.payloadHash.slice(0, 16)}…</td></tr>)}{!deliveries.data?.length && <tr><td colSpan={5} className="py-10 text-center text-slate-500">No delivery attempts have been made.</td></tr>}</tbody></table></CardContent></Card>
  </div>;
}
