import { useState } from "react";
import { CalendarDays, Car, ClipboardCheck, Fuel, PackagePlus, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const today = () => new Date().toISOString().slice(0, 10);
function Empty({ message }: { message: string }) { return <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">{message}</p>; }
function Section({ title, eyebrow, icon: Icon, children }: { title: string; eyebrow: string; icon: typeof TrendingUp; children: React.ReactNode }) { return <Card><CardContent className="p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2 text-[#147d66]"><Icon className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-widest text-[#147d66]">{eyebrow}</p><h3 className="font-bold text-slate-900">{title}</h3></div></div>{children}</CardContent></Card>; }

export default function OperationsExpansion() {
  const utils = trpc.useUtils();
  const forecasts = trpc.expansion.forecasts.list.useQuery(); const procurement = trpc.expansion.procurement.list.useQuery(); const vehicles = trpc.expansion.fleet.vehicles.list.useQuery(); const maintenance = trpc.expansion.fleet.maintenance.list.useQuery(); const fuel = trpc.expansion.fleet.fuel.list.useQuery(); const events = trpc.expansion.events.list.useQuery(); const coaching = trpc.expansion.coaching.list.useQuery();
  const createForecast = trpc.expansion.forecasts.create.useMutation({ onSuccess: () => { toast.success("Forecast recorded"); utils.expansion.forecasts.list.invalidate(); } }); const submitRequest = trpc.expansion.procurement.submit.useMutation({ onSuccess: () => { toast.success("Purchase request submitted"); utils.expansion.procurement.list.invalidate(); } }); const createVehicle = trpc.expansion.fleet.vehicles.create.useMutation({ onSuccess: () => { toast.success("Vehicle registered"); utils.expansion.fleet.vehicles.list.invalidate(); } }); const scheduleMaintenance = trpc.expansion.fleet.maintenance.schedule.useMutation({ onSuccess: () => { toast.success("Maintenance scheduled"); utils.expansion.fleet.maintenance.list.invalidate(); } }); const recordFuel = trpc.expansion.fleet.fuel.record.useMutation({ onSuccess: () => { toast.success("Fuel log recorded"); utils.expansion.fleet.fuel.list.invalidate(); } }); const createEvent = trpc.expansion.events.create.useMutation({ onSuccess: () => { toast.success("Event created"); utils.expansion.events.list.invalidate(); } }); const addCoaching = trpc.expansion.coaching.add.useMutation({ onSuccess: () => { toast.success("Coaching note recorded"); utils.expansion.coaching.list.invalidate(); } });
  const [forecast, setForecast] = useState({ productName: "", periodStart: today(), periodEnd: today(), value: "" }); const [request, setRequest] = useState({ productName: "", quantity: "", rationale: "" }); const [vehicle, setVehicle] = useState({ registrationNumber: "", makeModel: "" }); const [maintenanceForm, setMaintenanceForm] = useState({ vehicleId: "", type: "", dueDate: today() }); const [fuelForm, setFuelForm] = useState({ vehicleId: "", odometer: "", liters: "", totalCost: "" }); const [eventForm, setEventForm] = useState({ name: "", startsAt: today(), endsAt: today(), locationOrUrl: "" }); const [coach, setCoach] = useState({ visitLogId: "", note: "", flag: false });
  return <div className="space-y-6"><section className="rounded-3xl bg-[#10203d] p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-[#63e1ba]">MVP operations expansion</p><h2 className="mt-2 text-3xl font-bold">Forecast, procure, operate, engage, coach</h2><p className="mt-2 max-w-3xl text-sm text-slate-300">Tenant-scoped workflows are deliberately compact in this first release. Every lifecycle action is role-gated and recorded in the audit trail.</p></section>
    <div className="grid gap-6 xl:grid-cols-2"><Section eyebrow="Forecasting" title="Territory & product baseline forecast" icon={TrendingUp}><form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); createForecast.mutate({ productName: forecast.productName, periodStart: new Date(forecast.periodStart), periodEnd: new Date(forecast.periodEnd), method: "manual", forecastValue: Number(forecast.value) }); }}><Input placeholder="Product" value={forecast.productName} onChange={e => setForecast({ ...forecast, productName: e.target.value })} /><Input type="number" min="0" step="0.01" placeholder="Forecast value" value={forecast.value} onChange={e => setForecast({ ...forecast, value: e.target.value })} /><Input type="date" value={forecast.periodStart} onChange={e => setForecast({ ...forecast, periodStart: e.target.value })} /><Input type="date" value={forecast.periodEnd} onChange={e => setForecast({ ...forecast, periodEnd: e.target.value })} /><Button className="sm:col-span-2" disabled={createForecast.isPending}>Create draft forecast</Button></form><div className="mt-5 space-y-2">{forecasts.data?.length ? forecasts.data.slice(0, 4).map(item => <div key={item.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{item.productName} · {item.method}</span><b>{item.forecastValue}</b></div>) : <Empty message="No forecast records for this tenant yet." />}</div></Section>
      <Section eyebrow="Procurement" title="Simple purchase requests" icon={PackagePlus}><form className="mt-5 grid gap-3" onSubmit={event => { event.preventDefault(); submitRequest.mutate({ productName: request.productName, requestedQuantity: Number(request.quantity), rationale: request.rationale }); }}><Input placeholder="Product or sample name" value={request.productName} onChange={e => setRequest({ ...request, productName: e.target.value })} /><Input type="number" min="1" placeholder="Requested quantity" value={request.quantity} onChange={e => setRequest({ ...request, quantity: e.target.value })} /><Textarea placeholder="Operational rationale" value={request.rationale} onChange={e => setRequest({ ...request, rationale: e.target.value })} /><Button disabled={submitRequest.isPending}>Submit purchase request</Button></form><div className="mt-5 space-y-2">{procurement.data?.length ? procurement.data.slice(0, 4).map(item => <div key={item.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{item.productName} × {item.requestedQuantity}</span><b className="capitalize">{item.status}</b></div>) : <Empty message="No procurement requests for this tenant yet." />}</div></Section>
      <Section eyebrow="Fleet" title="Vehicle maintenance & fuel" icon={Car}><form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); createVehicle.mutate(vehicle); }}><Input placeholder="Registration" value={vehicle.registrationNumber} onChange={e => setVehicle({ ...vehicle, registrationNumber: e.target.value })} /><Input placeholder="Make / model" value={vehicle.makeModel} onChange={e => setVehicle({ ...vehicle, makeModel: e.target.value })} /><Button className="sm:col-span-2" disabled={createVehicle.isPending}>Register vehicle</Button></form><form className="mt-4 grid gap-3 sm:grid-cols-3" onSubmit={event => { event.preventDefault(); scheduleMaintenance.mutate({ vehicleId: maintenanceForm.vehicleId, maintenanceType: maintenanceForm.type, dueDate: new Date(maintenanceForm.dueDate) }); }}><Input placeholder="Vehicle ID" value={maintenanceForm.vehicleId} onChange={e => setMaintenanceForm({ ...maintenanceForm, vehicleId: e.target.value })} /><Input placeholder="Maintenance type" value={maintenanceForm.type} onChange={e => setMaintenanceForm({ ...maintenanceForm, type: e.target.value })} /><Input type="date" value={maintenanceForm.dueDate} onChange={e => setMaintenanceForm({ ...maintenanceForm, dueDate: e.target.value })} /><Button className="sm:col-span-3" disabled={scheduleMaintenance.isPending}>Schedule maintenance</Button></form><div className="mt-5 space-y-2">{vehicles.data?.length ? vehicles.data.slice(0, 3).map(item => <div key={item.id} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{item.registrationNumber}</b> · {item.makeModel} · {item.status}</div>) : <Empty message="Register a vehicle before recording maintenance or fuel." />}{maintenance.data?.slice(0, 2).map(item => <div key={item.id} className="rounded-lg border border-amber-100 bg-amber-50 p-3 text-sm">Maintenance: {item.maintenanceType} · {item.status}</div>)}</div></Section>
      <Section eyebrow="Fuel log" title="Manual refueling records" icon={Fuel}><form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); recordFuel.mutate({ vehicleId: fuelForm.vehicleId, filledAt: new Date(), odometerKm: Number(fuelForm.odometer), liters: Number(fuelForm.liters), totalCost: Number(fuelForm.totalCost) }); }}><Input placeholder="Vehicle ID" value={fuelForm.vehicleId} onChange={e => setFuelForm({ ...fuelForm, vehicleId: e.target.value })} /><Input type="number" placeholder="Odometer km" value={fuelForm.odometer} onChange={e => setFuelForm({ ...fuelForm, odometer: e.target.value })} /><Input type="number" step="0.01" placeholder="Liters" value={fuelForm.liters} onChange={e => setFuelForm({ ...fuelForm, liters: e.target.value })} /><Input type="number" step="0.01" placeholder="Total cost" value={fuelForm.totalCost} onChange={e => setFuelForm({ ...fuelForm, totalCost: e.target.value })} /><Button className="sm:col-span-2" disabled={recordFuel.isPending}>Record fuel</Button></form><div className="mt-5 space-y-2">{fuel.data?.length ? fuel.data.slice(0, 4).map(item => <div key={item.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{item.liters} L · {item.odometerKm} km</span><b>{item.totalCost} {item.currency}</b></div>) : <Empty message="No manual fuel entries yet." />}</div></Section>
      <Section eyebrow="Events" title="Medical events, webinars & launches" icon={CalendarDays}><form className="mt-5 grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); createEvent.mutate({ name: eventForm.name, eventType: "webinar", startsAt: new Date(eventForm.startsAt), endsAt: new Date(eventForm.endsAt), locationOrUrl: eventForm.locationOrUrl || undefined }); }}><Input placeholder="Event name" value={eventForm.name} onChange={e => setEventForm({ ...eventForm, name: e.target.value })} /><Input placeholder="Venue or webinar URL" value={eventForm.locationOrUrl} onChange={e => setEventForm({ ...eventForm, locationOrUrl: e.target.value })} /><Input type="date" value={eventForm.startsAt} onChange={e => setEventForm({ ...eventForm, startsAt: e.target.value })} /><Input type="date" value={eventForm.endsAt} onChange={e => setEventForm({ ...eventForm, endsAt: e.target.value })} /><Button className="sm:col-span-2" disabled={createEvent.isPending}>Create webinar event</Button></form><div className="mt-5 space-y-2">{events.data?.length ? events.data.slice(0, 4).map(item => <div key={item.id} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{item.name}</b> · {item.eventType} · {item.status}</div>) : <Empty message="No events scheduled for this tenant yet." />}</div></Section>
      <Section eyebrow="Manager coaching" title="Visit feedback & compliance flags" icon={ClipboardCheck}><form className="mt-5 grid gap-3" onSubmit={event => { event.preventDefault(); addCoaching.mutate({ visitLogId: coach.visitLogId, coachingNote: coach.note, complianceFlag: coach.flag }); }}><Input placeholder="Visit log ID" value={coach.visitLogId} onChange={e => setCoach({ ...coach, visitLogId: e.target.value })} /><Textarea placeholder="Specific coaching feedback" value={coach.note} onChange={e => setCoach({ ...coach, note: e.target.value })} /><label className="flex gap-2 text-sm"><input type="checkbox" checked={coach.flag} onChange={e => setCoach({ ...coach, flag: e.target.checked })} /> Flag for compliance follow-up</label><Button disabled={addCoaching.isPending}>Record coaching note</Button></form><div className="mt-5 space-y-2">{coaching.data?.length ? coaching.data.slice(0, 4).map(item => <div key={item.id} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{item.complianceFlag ? "Compliance flag" : "Coaching"}</b> · {item.acknowledgementStatus}</div>) : <Empty message="No coaching notes visible for this user yet." />}</div></Section></div></div>;
}
