import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Building2, CirclePlus, PauseCircle, PlayCircle } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const emptyForm = { legalName: "", displayName: "", slug: "", planTier: "starter" as const, region: "global", adminName: "", adminEmail: "", adminPassword: "" };

export default function TenantsPage() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const query = trpc.platform.listTenants.useQuery(undefined, { enabled: user?.role === "super_admin" });
  const provision = trpc.platform.provisionTenant.useMutation({ onSuccess: async () => { toast.success("Tenant provisioned and first administrator bootstrapped."); setForm(emptyForm); setShowForm(false); await utils.platform.listTenants.invalidate(); }, onError: error => toast.error(error.message) });
  const lifecycle = trpc.platform.changeLifecycle.useMutation({ onSuccess: async () => { toast.success("Tenant lifecycle change recorded."); await utils.platform.listTenants.invalidate(); }, onError: error => toast.error(error.message) });
  if (user?.role !== "super_admin") return <AccessDenied />;
  const submit = (event: FormEvent) => { event.preventDefault(); provision.mutate(form); };
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#1e9274]">Platform registry</p><h2 className="mt-2 text-2xl font-bold tracking-[-.035em]">Tenant management</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Provision companies, assign tiers, and control tenant lifecycle without exposing one company’s record set to another.</p></div><Button className="h-10 bg-[#147d66] hover:bg-[#0f6956]" onClick={() => setShowForm(!showForm)}><CirclePlus className="mr-2 h-4 w-4" />Provision tenant</Button></div>
    {showForm && <Card className="border-[#bfe7d9] bg-[#fbfffd] shadow-sm"><CardContent className="p-6"><form onSubmit={submit} className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><FormField label="Legal company name"><Input required value={form.legalName} onChange={event => setForm({ ...form, legalName: event.target.value })} placeholder="Northstar Pharmaceuticals Ltd." /></FormField><FormField label="Display name"><Input required value={form.displayName} onChange={event => setForm({ ...form, displayName: event.target.value })} placeholder="Northstar Pharma" /></FormField><FormField label="Tenant slug"><Input required value={form.slug} pattern="[a-z0-9-]{3,96}" onChange={event => setForm({ ...form, slug: event.target.value.toLowerCase() })} placeholder="northstar-pharma" /></FormField><FormField label="Plan tier"><select value={form.planTier} onChange={event => setForm({ ...form, planTier: event.target.value as typeof form.planTier })} className="h-10 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="starter">Starter</option><option value="growth">Growth</option><option value="enterprise">Enterprise</option><option value="regulated">Regulated</option></select></FormField><FormField label="Deployment region"><Input required value={form.region} onChange={event => setForm({ ...form, region: event.target.value })} placeholder="eu-central" /></FormField><div className="hidden lg:block" /><FormField label="First admin name"><Input required value={form.adminName} onChange={event => setForm({ ...form, adminName: event.target.value })} placeholder="Alex Morgan" /></FormField><FormField label="First admin email"><Input required type="email" value={form.adminEmail} onChange={event => setForm({ ...form, adminEmail: event.target.value })} placeholder="alex@northstar.example" /></FormField><FormField label="Initial admin password"><Input required type="password" minLength={14} value={form.adminPassword} onChange={event => setForm({ ...form, adminPassword: event.target.value })} placeholder="Minimum 14 characters" /></FormField><div className="md:col-span-2 lg:col-span-3 flex items-center justify-between rounded-xl bg-[#eef9f4] px-4 py-3"><p className="max-w-2xl text-xs leading-5 text-[#397162]">The password is hashed before storage. The new admin is initialized as an active tenant administrator; the provisioning event is appended to the tenant audit chain.</p><Button disabled={provision.isPending} className="ml-4 shrink-0 bg-[#147d66] hover:bg-[#0f6956]">{provision.isPending ? "Provisioning…" : "Create tenant"}</Button></div></form></CardContent></Card>}
    <Card className="overflow-hidden border-slate-200/80 bg-white"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-[.12em] text-slate-400"><tr><th className="px-6 py-4">Company</th><th className="px-4 py-4">Tier</th><th className="px-4 py-4">Billing</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Region</th><th className="px-6 py-4 text-right">Lifecycle action</th></tr></thead><tbody className="divide-y divide-slate-100">{query.isLoading && <tr><td colSpan={6} className="px-6 py-12 text-center text-sm text-slate-400">Loading tenant registry…</td></tr>}{!query.isLoading && query.data?.length === 0 && <tr><td colSpan={6} className="px-6 py-14 text-center"><Building2 className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3 text-sm font-semibold text-slate-600">No tenants provisioned yet</p><p className="mt-1 text-xs text-slate-400">Create the first company above to initialize its tenant boundary and administrator.</p></td></tr>}{query.data?.map(tenant => <tr key={tenant.id} className="hover:bg-slate-50/60"><td className="px-6 py-4"><p className="text-sm font-semibold text-slate-700">{tenant.displayName}</p><p className="mt-0.5 text-xs text-slate-400">{tenant.slug}</p></td><td className="px-4 py-4"><select aria-label={`Plan tier for ${tenant.displayName}`} value={tenant.planTier} disabled={lifecycle.isPending} onChange={event => lifecycle.mutate({ tenantId: tenant.id, planTier: event.target.value as "starter" | "growth" | "enterprise" | "regulated", reason: `Platform operator assigned the ${event.target.value} plan tier.` })} className="h-8 rounded-lg border border-[#dce4f4] bg-[#f6f8ff] px-2 text-xs font-semibold capitalize text-[#5662c5] outline-none focus:ring-2 focus:ring-[#b7c2f1]"><option value="starter">Starter</option><option value="growth">Growth</option><option value="enterprise">Enterprise</option><option value="regulated">Regulated</option></select></td><td className="px-4 py-4 text-sm capitalize text-slate-600">{tenant.billingStatus.replace("_", " ")}</td><td className="px-4 py-4"><StatusBadge status={tenant.status} /></td><td className="px-4 py-4 text-sm text-slate-500">{tenant.region}</td><td className="px-6 py-4 text-right"><Button size="sm" variant="outline" className="h-8 border-slate-200 text-xs" disabled={lifecycle.isPending} onClick={() => lifecycle.mutate({ tenantId: tenant.id, status: tenant.status === "active" ? "suspended" : "active", reason: `Platform operator changed tenant status to ${tenant.status === "active" ? "suspended" : "active"}.` })}>{tenant.status === "active" ? <><PauseCircle className="mr-1.5 h-3.5 w-3.5" />Suspend</> : <><PlayCircle className="mr-1.5 h-3.5 w-3.5" />Reactivate</>}</Button></td></tr>)}</tbody></table></div></CardContent></Card></div>;
}

export function AccessDenied() { return <Card className="border-slate-200 bg-white"><CardContent className="p-10 text-center"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#be7427]">Restricted area</p><h2 className="mt-2 text-xl font-bold">Your current role cannot open this module.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">The route guard has preserved your tenant and role boundary. Ask a platform administrator to adjust your access through an audited lifecycle change.</p></CardContent></Card>; }
function FormField({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-2"><Label>{label}</Label>{children}</label>; }
function StatusBadge({ status }: { status: string }) { const style = status === "active" ? "bg-[#e9f8f2] text-[#188064]" : status === "suspended" ? "bg-[#fff1ef] text-[#bf544b]" : "bg-[#f4f2ec] text-[#817663]"; return <Badge className={`border-0 capitalize ${style} hover:${style}`}>{status}</Badge>; }
