import { describe, expect, it, vi } from "vitest";
const update = vi.fn(() => ({ set: vi.fn(() => ({ where: vi.fn(async () => undefined) })) }));
const db = { select: vi.fn(() => ({ from: vi.fn(() => ({ where: vi.fn(() => ({ limit: vi.fn(async () => []), orderBy: vi.fn(async () => []) })) })) })), insert: vi.fn(() => ({ values: vi.fn(async () => undefined) })), update };
vi.mock("./db", () => ({ getDb: async () => db, getTenantById: async (id: string) => ({ id, status: "active" }), appendAuditEvent: vi.fn(async () => undefined), findLocalUser: vi.fn(), getUserByOpenId: vi.fn(), upsertUser: vi.fn() }));
const manager = { id: 90, openId: "local:manager", tenantId: "tenant-a", name: "Manager", email: "manager@example.com", passwordHash: null, loginMethod: "local_jwt", role: "manager" as const, department: null, territory: null, hireDate: null, status: "active" as const, createdAt: new Date(), updatedAt: new Date(), createdBy: 1, lastSignedIn: new Date() };
const rep = { ...manager, id: 91, openId: "local:rep", email: "rep@example.com", role: "rep" as const };
describe("analytics procedure isolation", () => {
  it("keeps seeded tenant-A analytics history and alerts out of a tenant-B caller result", async () => { const { appRouter } = await import("./routers"); const seededQuery = { id: "query-a", tenantId: "tenant-a", userId: 90, question: "Visits", status: "completed" }; const seededAlert = { id: "alert-a", tenantId: "tenant-a", status: "open", anomalyType: "expense_outlier" }; const response = (rows: unknown[]) => ({ from: vi.fn(() => ({ where: vi.fn(() => ({ limit: vi.fn(async () => rows), orderBy: vi.fn(async () => rows) })) })) }); db.select.mockImplementationOnce(() => response([seededQuery]) as any).mockImplementationOnce(() => response([seededAlert]) as any); const tenantA = appRouter.createCaller({ user: manager, req: { headers: {} } as any, res: {} as any }); await expect(tenantA.analytics.history()).resolves.toEqual([seededQuery]); await expect(tenantA.analytics.alerts.list()).resolves.toEqual([seededAlert]); db.select.mockImplementationOnce(() => response([]) as any).mockImplementationOnce(() => response([]) as any); const tenantB = appRouter.createCaller({ user: { ...manager, tenantId: "tenant-b" }, req: { headers: {} } as any, res: {} as any }); await expect(tenantB.analytics.history()).resolves.toEqual([]); await expect(tenantB.analytics.alerts.list()).resolves.toEqual([]); });
  it("rejects a tenant-A review for a record that does not resolve in the active tenant", async () => { const { appRouter } = await import("./routers"); const caller = appRouter.createCaller({ user: manager, req: { headers: {} } as any, res: {} as any }); await expect(caller.analytics.alerts.review({ id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", action: "resolved" })).rejects.toThrow("Alert was not found in the active tenant"); expect(update).not.toHaveBeenCalled(); });
  it("rejects a rep attempting to review an anomaly alert before any database mutation", async () => { const { appRouter } = await import("./routers"); const caller = appRouter.createCaller({ user: rep, req: { headers: {} } as any, res: {} as any }); await expect(caller.analytics.alerts.review({ id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", action: "resolved" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
});
