import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";
import { and, eq } from "drizzle-orm";
import { accounts, anomalyAlerts, expenseReports, geofenceEvents, plannedVisits, repLocationEvents, repShifts, users, visitLogs } from "../../drizzle/schema";
import { getDb } from "../db";
export type BiDashboard = { title: string; role: string; kpis: Array<{ label: string; value: number; unit?: string }>; rows: Array<Record<string, string | number>> };
export async function buildBiDashboard(tenantId: string, role: string, userId: number): Promise<BiDashboard> { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [visits, plans, shifts, pings, alerts, expenses, tenantUsers, tenantAccounts, geo] = await Promise.all([db.select().from(visitLogs).where(and(eq(visitLogs.tenantId, tenantId), ...(role === "rep" ? [eq(visitLogs.repUserId, userId)] : []))), db.select().from(plannedVisits).where(and(eq(plannedVisits.tenantId, tenantId), ...(role === "rep" ? [eq(plannedVisits.repUserId, userId)] : []))), db.select().from(repShifts).where(and(eq(repShifts.tenantId, tenantId), ...(role === "rep" ? [eq(repShifts.repUserId, userId)] : []))), db.select().from(repLocationEvents).where(and(eq(repLocationEvents.tenantId, tenantId), ...(role === "rep" ? [eq(repLocationEvents.repUserId, userId)] : []))), db.select().from(anomalyAlerts).where(eq(anomalyAlerts.tenantId, tenantId)), db.select().from(expenseReports).where(eq(expenseReports.tenantId, tenantId)), db.select().from(users).where(eq(users.tenantId, tenantId)), db.select().from(accounts).where(and(eq(accounts.tenantId, tenantId), eq(accounts.status, "active"))), db.select().from(geofenceEvents).where(eq(geofenceEvents.tenantId, tenantId))]); const coverage = plans.length ? Math.round((visits.length / plans.length) * 100) : 0;
if (role === "rep") return { title: "Personal field performance", role, kpis: [{ label: "Call coverage", value: coverage, unit: "%" }, { label: "Recorded calls", value: visits.length }, { label: "Planned calls", value: plans.length }], rows: plans.map(p => ({ priority: p.priority, status: p.status, planned: p.plannedStartAt.toISOString().slice(0,10) })) };
if (role === "fleet") return { title: "Fleet operations", role, kpis: [{ label: "Active shifts", value: shifts.filter(s => s.status === "active").length }, { label: "Telemetry pings", value: pings.length }, { label: "Territory alerts", value: geo.filter(g => g.eventType === "far" || g.eventType === "exit").length }], rows: shifts.map(s => ({ repUserId: s.repUserId, status: s.status, started: s.startedAt.toISOString() })) };
if (role === "exec") return { title: "Executive cross-module KPIs", role, kpis: [{ label: "Active accounts", value: tenantAccounts.length }, { label: "Recorded visits", value: visits.length }, { label: "Open alerts", value: alerts.filter(a => a.status === "open").length }, { label: "Approved expense", value: expenses.filter(e => e.status === "approved" || e.status === "reimbursed").reduce((s,e)=>s+Number(e.amount),0), unit: "USD" }], rows: [{ employees: tenantUsers.length, accounts: tenantAccounts.length, visits: visits.length, alerts: alerts.filter(a=>a.status==="open").length }] };
const reps = tenantUsers.filter(u => u.role === "rep"); return { title: "Manager team coverage", role: "manager", kpis: [{ label: "Team coverage", value: coverage, unit: "%" }, { label: "Active reps", value: reps.length }, { label: "Open alerts", value: alerts.filter(a=>a.status==="open").length }], rows: reps.map(rep => ({ rep: rep.name ?? `Rep ${rep.id}`, visits: visits.filter(v=>v.repUserId===rep.id).length, planned: plans.filter(p=>p.repUserId===rep.id).length })) };
}
export function exportBi(dashboard: BiDashboard, format: "xlsx" | "pdf") { const rows = dashboard.rows.length ? dashboard.rows : dashboard.kpis.map(k => ({ metric: k.label, value: `${k.value}${k.unit ?? ""}` })); if (format === "xlsx") { const sheet = XLSX.utils.json_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, "Report"); return { mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", base64: XLSX.write(book, { type: "base64", bookType: "xlsx" }), extension: "xlsx" }; } const doc = new PDFDocument({ margin: 42 }); const chunks: Buffer[] = []; doc.on("data", c => chunks.push(c)); doc.fontSize(20).text(dashboard.title).moveDown().fontSize(10).text(`Role: ${dashboard.role}`).moveDown(); dashboard.kpis.forEach(k => doc.text(`${k.label}: ${k.value}${k.unit ?? ""}`)); doc.moveDown(); rows.forEach(row => doc.text(Object.entries(row).map(([k,v]) => `${k}: ${v}`).join("  |  "))); doc.end(); return new Promise<{mimeType:string;base64:string;extension:string}>(resolve => doc.on("end", () => resolve({ mimeType: "application/pdf", base64: Buffer.concat(chunks).toString("base64"), extension: "pdf" }))); }
